set(_AMENT_PACKAGE_NAME "nebula_ros")
set(nebula_ros_VERSION "0.1.0")
set(nebula_ros_MAINTAINER "MAP IV <contact@map4.jp>")
set(nebula_ros_BUILD_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "pcl_conversions" "rclcpp" "rclcpp_components" "yaml-cpp")
set(nebula_ros_BUILDTOOL_DEPENDS "ament_cmake_auto" "ros_environment")
set(nebula_ros_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "pcl_conversions" "rclcpp" "rclcpp_components" "yaml-cpp")
set(nebula_ros_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_ros_EXEC_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "pcl_conversions" "rclcpp" "rclcpp_components" "yaml-cpp")
set(nebula_ros_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto")
set(nebula_ros_GROUP_DEPENDS )
set(nebula_ros_MEMBER_OF_GROUPS )
set(nebula_ros_DEPRECATED "")
set(nebula_ros_EXPORT_TAGS)
list(APPEND nebula_ros_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
