set(_AMENT_PACKAGE_NAME "rtklib_msgs")
set(rtklib_msgs_VERSION "0.0.0")
set(rtklib_msgs_MAINTAINER "megken <megken@todo.todo>")
set(rtklib_msgs_BUILD_DEPENDS "rosidl_default_generators" "builtin_interfaces" "std_msgs" "geometry_msgs" "sensor_msgs")
set(rtklib_msgs_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(rtklib_msgs_BUILD_EXPORT_DEPENDS "builtin_interfaces" "std_msgs" "geometry_msgs" "sensor_msgs")
set(rtklib_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(rtklib_msgs_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "std_msgs" "geometry_msgs" "sensor_msgs")
set(rtklib_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rtklib_msgs_GROUP_DEPENDS )
set(rtklib_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(rtklib_msgs_DEPRECATED "")
set(rtklib_msgs_EXPORT_TAGS)
list(APPEND rtklib_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
