set(_AMENT_PACKAGE_NAME "mcity_abc")
set(mcity_abc_VERSION "0.1.0")
set(mcity_abc_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_abc_BUILD_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "tier4_debug_msgs" "dummy_perception_publisher")
set(mcity_abc_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_abc_BUILD_EXPORT_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "tier4_debug_msgs" "dummy_perception_publisher")
set(mcity_abc_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_abc_EXEC_DEPENDS "ros2launch" "tf2_ros" "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "tier4_debug_msgs" "dummy_perception_publisher")
set(mcity_abc_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_abc_GROUP_DEPENDS )
set(mcity_abc_MEMBER_OF_GROUPS )
set(mcity_abc_DEPRECATED "")
set(mcity_abc_EXPORT_TAGS)
list(APPEND mcity_abc_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
