set(_AMENT_PACKAGE_NAME "boost_udp_driver")
set(boost_udp_driver_VERSION "1.2.0")
set(boost_udp_driver_MAINTAINER "Joshua Whitley <whitleysoftwareservices@gmail.com>")
set(boost_udp_driver_BUILD_DEPENDS "boost" "boost_io_context" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs" "udp_msgs")
set(boost_udp_driver_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(boost_udp_driver_BUILD_EXPORT_DEPENDS "boost" "boost_io_context" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs" "udp_msgs")
set(boost_udp_driver_BUILDTOOL_EXPORT_DEPENDS )
set(boost_udp_driver_EXEC_DEPENDS "boost" "boost_io_context" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs" "udp_msgs")
set(boost_udp_driver_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(boost_udp_driver_GROUP_DEPENDS )
set(boost_udp_driver_MEMBER_OF_GROUPS )
set(boost_udp_driver_DEPRECATED "")
set(boost_udp_driver_EXPORT_TAGS)
list(APPEND boost_udp_driver_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
