set(_AMENT_PACKAGE_NAME "nebula_examples")
set(nebula_examples_VERSION "0.1.0")
set(nebula_examples_MAINTAINER "Perception Engine <contact@perceptionengine.jp>")
set(nebula_examples_BUILD_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_ros" "pandar_msgs" "pcl_conversions" "pcl_msgs" "rclcpp" "rclcpp_components" "rosbag2_cpp" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_examples_BUILDTOOL_DEPENDS "ament_cmake_auto" "ros_environment")
set(nebula_examples_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_ros" "pandar_msgs" "pcl_conversions" "pcl_msgs" "rclcpp" "rclcpp_components" "rosbag2_cpp" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_examples_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_examples_EXEC_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_ros" "pandar_msgs" "pcl_conversions" "pcl_msgs" "rclcpp" "rclcpp_components" "rosbag2_cpp" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_examples_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(nebula_examples_GROUP_DEPENDS )
set(nebula_examples_MEMBER_OF_GROUPS )
set(nebula_examples_DEPRECATED "")
set(nebula_examples_EXPORT_TAGS)
list(APPEND nebula_examples_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
