# CMake generated Testfile for 
# Source directory: /home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension
# Build directory: /home/mtl12345/autoware/build/lanelet2_extension
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(message_conversion-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/message_conversion-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/message_conversion-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/message_conversion-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/message_conversion-test.gtest.xml")
set_tests_properties(message_conversion-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/message_conversion-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;83;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
add_test(projector-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/projector-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/projector-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/projector-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/projector-test.gtest.xml")
set_tests_properties(projector-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/projector-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;85;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
add_test(query-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/query-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/query-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/query-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/query-test.gtest.xml")
set_tests_properties(query-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/query-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;87;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
add_test(regulatory_elements-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/regulatory_elements-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/regulatory_elements-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/regulatory_elements-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/regulatory_elements-test.gtest.xml")
set_tests_properties(regulatory_elements-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/regulatory_elements-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;89;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
add_test(utilities-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/utilities-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/utilities-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/utilities-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/utilities-test.gtest.xml")
set_tests_properties(utilities-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/utilities-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;91;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
add_test(route-test "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_ros/cmake/run_test_isolated.py" "/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/route-test.gtest.xml" "--package-name" "lanelet2_extension" "--output-file" "/home/mtl12345/autoware/build/lanelet2_extension/ament_cmake_gtest/route-test.txt" "--command" "/home/mtl12345/autoware/build/lanelet2_extension/route-test" "--gtest_output=xml:/home/mtl12345/autoware/build/lanelet2_extension/test_results/lanelet2_extension/route-test.gtest.xml")
set_tests_properties(route-test PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/lanelet2_extension/route-test" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/lanelet2_extension" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/opt/ros/humble/share/ament_cmake_ros/cmake/ament_add_ros_isolated_gtest.cmake;33;ament_add_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;97;ament_add_ros_isolated_gtest;/home/mtl12345/autoware/src/core/autoware_common/tmp/lanelet2_extension/CMakeLists.txt;0;")
subdirs("gtest")
