set(_AMENT_PACKAGE_NAME "qp_interface")
set(qp_interface_VERSION "1.0.0")
set(qp_interface_MAINTAINER "Takayuki Murooka <takayuki.murooka@tier4.jp>, Fumiya Watanabe <fumiya.watanabe@tier4.jp>, Maxime CLEMENT <maxime.clement@tier4.jp>, Satoshi Ota <satoshi.ota@tier4.jp>")
set(qp_interface_BUILD_DEPENDS "eigen" "osqp_vendor" "proxsuite" "rclcpp" "rclcpp_components")
set(qp_interface_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(qp_interface_BUILD_EXPORT_DEPENDS "eigen" "osqp_vendor" "proxsuite" "rclcpp" "rclcpp_components")
set(qp_interface_BUILDTOOL_EXPORT_DEPENDS )
set(qp_interface_EXEC_DEPENDS "eigen" "osqp_vendor" "proxsuite" "rclcpp" "rclcpp_components")
set(qp_interface_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common" "eigen")
set(qp_interface_GROUP_DEPENDS )
set(qp_interface_MEMBER_OF_GROUPS )
set(qp_interface_DEPRECATED "")
set(qp_interface_EXPORT_TAGS)
list(APPEND qp_interface_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
