set(_AMENT_PACKAGE_NAME "perception_utils")
set(perception_utils_VERSION "0.1.0")
set(perception_utils_MAINTAINER "Satoshi Tanaka <satoshi.tanaka@tier4.jp>, Yusuke Muramatsu <yusuke.muramatsu@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(perception_utils_BUILD_DEPENDS "rclcpp")
set(perception_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(perception_utils_BUILD_EXPORT_DEPENDS "rclcpp")
set(perception_utils_BUILDTOOL_EXPORT_DEPENDS )
set(perception_utils_EXEC_DEPENDS "rclcpp")
set(perception_utils_TEST_DEPENDS )
set(perception_utils_GROUP_DEPENDS )
set(perception_utils_MEMBER_OF_GROUPS )
set(perception_utils_DEPRECATED "")
set(perception_utils_EXPORT_TAGS)
list(APPEND perception_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
