set(_AMENT_PACKAGE_NAME "traffic_light_arbiter")
set(traffic_light_arbiter_VERSION "0.1.0")
set(traffic_light_arbiter_MAINTAINER "Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(traffic_light_arbiter_BUILD_DEPENDS "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_core" "lanelet2_extension" "rclcpp" "rclcpp_components")
set(traffic_light_arbiter_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(traffic_light_arbiter_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_core" "lanelet2_extension" "rclcpp" "rclcpp_components")
set(traffic_light_arbiter_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_arbiter_EXEC_DEPENDS "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_core" "lanelet2_extension" "rclcpp" "rclcpp_components")
set(traffic_light_arbiter_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(traffic_light_arbiter_GROUP_DEPENDS )
set(traffic_light_arbiter_MEMBER_OF_GROUPS )
set(traffic_light_arbiter_DEPRECATED "")
set(traffic_light_arbiter_EXPORT_TAGS)
list(APPEND traffic_light_arbiter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
