set(_AMENT_PACKAGE_NAME "radar_tracks_noise_filter")
set(radar_tracks_noise_filter_VERSION "0.1.0")
set(radar_tracks_noise_filter_MAINTAINER "Sathshi Tanaka <satoshi.tanaka@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(radar_tracks_noise_filter_BUILD_DEPENDS "autoware_cmake" "geometry_msgs" "radar_msgs" "rclcpp" "rclcpp_components")
set(radar_tracks_noise_filter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(radar_tracks_noise_filter_BUILD_EXPORT_DEPENDS "geometry_msgs" "radar_msgs" "rclcpp" "rclcpp_components")
set(radar_tracks_noise_filter_BUILDTOOL_EXPORT_DEPENDS )
set(radar_tracks_noise_filter_EXEC_DEPENDS "geometry_msgs" "radar_msgs" "rclcpp" "rclcpp_components")
set(radar_tracks_noise_filter_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(radar_tracks_noise_filter_GROUP_DEPENDS )
set(radar_tracks_noise_filter_MEMBER_OF_GROUPS )
set(radar_tracks_noise_filter_DEPRECATED "")
set(radar_tracks_noise_filter_EXPORT_TAGS)
list(APPEND radar_tracks_noise_filter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
