set(_AMENT_PACKAGE_NAME "object_velocity_splitter")
set(object_velocity_splitter_VERSION "0.1.0")
set(object_velocity_splitter_MAINTAINER "Sathshi Tanaka <satoshi.tanaka@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>, Yoshi Ri <yoshi.ri@tier4.jp>")
set(object_velocity_splitter_BUILD_DEPENDS "autoware_cmake" "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(object_velocity_splitter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(object_velocity_splitter_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(object_velocity_splitter_BUILDTOOL_EXPORT_DEPENDS )
set(object_velocity_splitter_EXEC_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(object_velocity_splitter_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(object_velocity_splitter_GROUP_DEPENDS )
set(object_velocity_splitter_MEMBER_OF_GROUPS )
set(object_velocity_splitter_DEPRECATED "")
set(object_velocity_splitter_EXPORT_TAGS)
list(APPEND object_velocity_splitter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
