set(_AMENT_PACKAGE_NAME "autoware_auto_common")
set(autoware_auto_common_VERSION "1.0.0")
set(autoware_auto_common_MAINTAINER "Apex.AI, Inc. <opensource@apex.ai>, Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>, Satoshi Ota <satoshi.ota@tier4.jp>")
set(autoware_auto_common_BUILD_DEPENDS "builtin_interfaces" "eigen")
set(autoware_auto_common_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(autoware_auto_common_BUILD_EXPORT_DEPENDS "builtin_interfaces" "eigen")
set(autoware_auto_common_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_auto_common_EXEC_DEPENDS "builtin_interfaces" "eigen")
set(autoware_auto_common_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common" "geometry_msgs")
set(autoware_auto_common_GROUP_DEPENDS )
set(autoware_auto_common_MEMBER_OF_GROUPS )
set(autoware_auto_common_DEPRECATED "")
set(autoware_auto_common_EXPORT_TAGS)
list(APPEND autoware_auto_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
