set(_AMENT_PACKAGE_NAME "geography_utils")
set(geography_utils_VERSION "0.1.0")
set(geography_utils_MAINTAINER "Koji Minoda <koji.minoda@tier4.jp>")
set(geography_utils_BUILD_DEPENDS "geographic_msgs" "geographiclib" "geometry_msgs" "lanelet2_extension" "lanelet2_io" "tier4_map_msgs")
set(geography_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(geography_utils_BUILD_EXPORT_DEPENDS "geographic_msgs" "geographiclib" "geometry_msgs" "lanelet2_extension" "lanelet2_io" "tier4_map_msgs")
set(geography_utils_BUILDTOOL_EXPORT_DEPENDS )
set(geography_utils_EXEC_DEPENDS "geographic_msgs" "geographiclib" "geometry_msgs" "lanelet2_extension" "lanelet2_io" "tier4_map_msgs")
set(geography_utils_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(geography_utils_GROUP_DEPENDS )
set(geography_utils_MEMBER_OF_GROUPS )
set(geography_utils_DEPRECATED "")
set(geography_utils_EXPORT_TAGS)
list(APPEND geography_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
