set(_AMENT_PACKAGE_NAME "control_validator")
set(control_validator_VERSION "0.1.0")
set(control_validator_MAINTAINER "Kyoichi Sugahara <kyoichi.sugahara@tier4.jp>, Takamasa Horibe <takamasa.horibe@tier4.jp>, Makoto Kurihara <makoto.kurihara@tier4.jp>")
set(control_validator_BUILD_DEPENDS "rosidl_default_generators" "autoware_auto_planning_msgs" "diagnostic_updater" "geometry_msgs" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(control_validator_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(control_validator_BUILD_EXPORT_DEPENDS "autoware_auto_planning_msgs" "diagnostic_updater" "geometry_msgs" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(control_validator_BUILDTOOL_EXPORT_DEPENDS )
set(control_validator_EXEC_DEPENDS "rosidl_default_runtime" "autoware_auto_planning_msgs" "diagnostic_updater" "geometry_msgs" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(control_validator_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(control_validator_GROUP_DEPENDS )
set(control_validator_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(control_validator_DEPRECATED "")
set(control_validator_EXPORT_TAGS)
list(APPEND control_validator_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
