float64 timestamp
int64   rtk_timestamp_sec
int64   rtk_timestamp_nsec

int64   rtk_keep_count
int64   rtk_seq_num
int16   rtk_gps_status	
int16   rtk_gps_service

int64   mobileye_keep_count
int16   mobileye_lanes_num 

int64   dsrc_bsm_keep_count
int64 	dsrc_bsm_num
int64   dsrc_spat_keep_count
int64 	dsrc_spat_num

int64   ibeo_points_keep_count
int64 	ibeo_points_num
int64   ibeo_objects_keep_count
int64 	ibeo_objests_num

int64   velodyne_points_keep_count
int64 	velodyne_points_num
 
bool   throttle_enabled
bool   throttle_override
bool   throttle_driver
bool   throttle_timeout

bool   brake_enabled
bool   brake_override
bool   brake_driver
bool   brake_timeout

bool   steer_enabled
bool   steer_override
bool   steer_timeout

