set(_AMENT_PACKAGE_NAME "pandar_msgs")
set(pandar_msgs_VERSION "0.0.0")
set(pandar_msgs_MAINTAINER "hirakawa <shinnosuke.hirakawa@tier4.jp>")
set(pandar_msgs_BUILD_DEPENDS "builtin_interfaces" "std_msgs")
set(pandar_msgs_BUILDTOOL_DEPENDS "ament_cmake_auto" "rosidl_default_generators")
set(pandar_msgs_BUILD_EXPORT_DEPENDS "builtin_interfaces" "std_msgs")
set(pandar_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(pandar_msgs_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "std_msgs")
set(pandar_msgs_TEST_DEPENDS )
set(pandar_msgs_GROUP_DEPENDS )
set(pandar_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(pandar_msgs_DEPRECATED "")
set(pandar_msgs_EXPORT_TAGS)
list(APPEND pandar_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
