set(_AMENT_PACKAGE_NAME "nebula_tests")
set(nebula_tests_VERSION "0.1.0")
set(nebula_tests_MAINTAINER "MAP IV <contact@map4.jp>")
set(nebula_tests_BUILD_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "nebula_ros" "pcl_conversions" "rclcpp" "rclcpp_components" "rosbag2_cpp")
set(nebula_tests_BUILDTOOL_DEPENDS "ament_cmake_auto" "ros_environment")
set(nebula_tests_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "nebula_ros" "pcl_conversions" "rclcpp" "rclcpp_components" "rosbag2_cpp")
set(nebula_tests_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_tests_EXEC_DEPENDS "diagnostic_msgs" "diagnostic_updater" "libpcl-all-dev" "nebula_common" "nebula_decoders" "nebula_hw_interfaces" "nebula_ros" "pcl_conversions" "rclcpp" "rclcpp_components" "rosbag2_cpp")
set(nebula_tests_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto")
set(nebula_tests_GROUP_DEPENDS )
set(nebula_tests_MEMBER_OF_GROUPS )
set(nebula_tests_DEPRECATED "")
set(nebula_tests_EXPORT_TAGS)
list(APPEND nebula_tests_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
