set(_AMENT_PACKAGE_NAME "autoware_utils")
set(autoware_utils_VERSION "0.1.0")
set(autoware_utils_MAINTAINER "Ryohsuke Mitsudome <ryohsuke.mitsudome@tier4.jp>, Esteve Fernandez <esteve.fernandez@tier4.jp>")
set(autoware_utils_BUILD_DEPENDS "builtin_interfaces" "rclcpp")
set(autoware_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(autoware_utils_BUILD_EXPORT_DEPENDS "builtin_interfaces" "rclcpp")
set(autoware_utils_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_utils_EXEC_DEPENDS "builtin_interfaces" "rclcpp")
set(autoware_utils_TEST_DEPENDS "ament_cmake_ros")
set(autoware_utils_GROUP_DEPENDS )
set(autoware_utils_MEMBER_OF_GROUPS )
set(autoware_utils_DEPRECATED "")
set(autoware_utils_EXPORT_TAGS)
list(APPEND autoware_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
