set(_AMENT_PACKAGE_NAME "path_smoother")
set(path_smoother_VERSION "0.1.0")
set(path_smoother_MAINTAINER "Takayuki Murooka <takayuki.murooka@tier4.jp>, Maxime CLEMENT <maxime.clement@tier4.jp>")
set(path_smoother_BUILD_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs")
set(path_smoother_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(path_smoother_BUILD_EXPORT_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs")
set(path_smoother_BUILDTOOL_EXPORT_DEPENDS )
set(path_smoother_EXEC_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs")
set(path_smoother_TEST_DEPENDS "ament_cmake_ros" "ament_index_python" "ament_lint_auto" "autoware_lint_common" "autoware_testing" "fake_test_node")
set(path_smoother_GROUP_DEPENDS )
set(path_smoother_MEMBER_OF_GROUPS )
set(path_smoother_DEPRECATED "")
set(path_smoother_EXPORT_TAGS)
list(APPEND path_smoother_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
