set(_AMENT_PACKAGE_NAME "bezier_sampler")
set(bezier_sampler_VERSION "0.0.1")
set(bezier_sampler_MAINTAINER "Maxime CLEMENT <maxime.clement@tier4.jp>")
set(bezier_sampler_BUILD_DEPENDS "autoware_cmake" "eigen" "sampler_common")
set(bezier_sampler_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(bezier_sampler_BUILD_EXPORT_DEPENDS "eigen" "sampler_common")
set(bezier_sampler_BUILDTOOL_EXPORT_DEPENDS )
set(bezier_sampler_EXEC_DEPENDS "eigen" "sampler_common")
set(bezier_sampler_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(bezier_sampler_GROUP_DEPENDS )
set(bezier_sampler_MEMBER_OF_GROUPS )
set(bezier_sampler_DEPRECATED "")
set(bezier_sampler_EXPORT_TAGS)
list(APPEND bezier_sampler_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
