set(_AMENT_PACKAGE_NAME "boost_serial_driver")
set(boost_serial_driver_VERSION "1.2.0")
set(boost_serial_driver_MAINTAINER "Joshua Whitley <whitleysoftwareservices@gmail.com>")
set(boost_serial_driver_BUILD_DEPENDS "libboost-dev" "boost_io_context" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs")
set(boost_serial_driver_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(boost_serial_driver_BUILD_EXPORT_DEPENDS "boost_io_context" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs")
set(boost_serial_driver_BUILDTOOL_EXPORT_DEPENDS )
set(boost_serial_driver_EXEC_DEPENDS "boost_io_context" "rclcpp" "rclcpp_components" "rclcpp_lifecycle" "std_msgs")
set(boost_serial_driver_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(boost_serial_driver_GROUP_DEPENDS )
set(boost_serial_driver_MEMBER_OF_GROUPS )
set(boost_serial_driver_DEPRECATED "")
set(boost_serial_driver_EXPORT_TAGS)
list(APPEND boost_serial_driver_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
