set(_AMENT_PACKAGE_NAME "traffic_light_recognition_marker_publisher")
set(traffic_light_recognition_marker_publisher_VERSION "0.0.0")
set(traffic_light_recognition_marker_publisher_MAINTAINER "Tomoya Kimura <tomoya.kimura@tier4.jp>, Takeshi Miura <takeshi.miura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>")
set(traffic_light_recognition_marker_publisher_BUILD_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_perception_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "visualization_msgs")
set(traffic_light_recognition_marker_publisher_BUILDTOOL_DEPENDS "ament_cmake" "autoware_cmake")
set(traffic_light_recognition_marker_publisher_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_perception_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "visualization_msgs")
set(traffic_light_recognition_marker_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_recognition_marker_publisher_EXEC_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_perception_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "visualization_msgs")
set(traffic_light_recognition_marker_publisher_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(traffic_light_recognition_marker_publisher_GROUP_DEPENDS )
set(traffic_light_recognition_marker_publisher_MEMBER_OF_GROUPS )
set(traffic_light_recognition_marker_publisher_DEPRECATED "")
set(traffic_light_recognition_marker_publisher_EXPORT_TAGS)
list(APPEND traffic_light_recognition_marker_publisher_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
