set(_AMENT_PACKAGE_NAME "behavior_velocity_crosswalk_module")
set(behavior_velocity_crosswalk_module_VERSION "0.1.0")
set(behavior_velocity_crosswalk_module_MAINTAINER "Satoshi Ota <satoshi.ota@tier4.jp>, Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>, Takayuki Murooka <takayuki.murooka@tier4.jp>")
set(behavior_velocity_crosswalk_module_BUILD_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pcl_conversions" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_debug_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_crosswalk_module_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake" "eigen3_cmake_module")
set(behavior_velocity_crosswalk_module_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pcl_conversions" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_debug_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_crosswalk_module_BUILDTOOL_EXPORT_DEPENDS )
set(behavior_velocity_crosswalk_module_EXEC_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pcl_conversions" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_debug_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_crosswalk_module_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(behavior_velocity_crosswalk_module_GROUP_DEPENDS )
set(behavior_velocity_crosswalk_module_MEMBER_OF_GROUPS )
set(behavior_velocity_crosswalk_module_DEPRECATED "")
set(behavior_velocity_crosswalk_module_EXPORT_TAGS)
list(APPEND behavior_velocity_crosswalk_module_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
