set(_AMENT_PACKAGE_NAME "sampler_common")
set(sampler_common_VERSION "0.0.1")
set(sampler_common_MAINTAINER "Maxime CLEMENT <maxime.clement@tier4.jp>")
set(sampler_common_BUILD_DEPENDS "autoware_cmake" "interpolation")
set(sampler_common_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(sampler_common_BUILD_EXPORT_DEPENDS "interpolation")
set(sampler_common_BUILDTOOL_EXPORT_DEPENDS )
set(sampler_common_EXEC_DEPENDS "interpolation")
set(sampler_common_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(sampler_common_GROUP_DEPENDS )
set(sampler_common_MEMBER_OF_GROUPS )
set(sampler_common_DEPRECATED "")
set(sampler_common_EXPORT_TAGS)
list(APPEND sampler_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
