set(_AMENT_PACKAGE_NAME "frenet_planner")
set(frenet_planner_VERSION "0.0.1")
set(frenet_planner_MAINTAINER "Maxime CLEMENT <maxime.clement@tier4.jp>")
set(frenet_planner_BUILD_DEPENDS "autoware_cmake" "autoware_auto_common" "sampler_common")
set(frenet_planner_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(frenet_planner_BUILD_EXPORT_DEPENDS "autoware_auto_common" "sampler_common")
set(frenet_planner_BUILDTOOL_EXPORT_DEPENDS )
set(frenet_planner_EXEC_DEPENDS "autoware_auto_common" "sampler_common")
set(frenet_planner_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(frenet_planner_GROUP_DEPENDS )
set(frenet_planner_MEMBER_OF_GROUPS )
set(frenet_planner_DEPRECATED "")
set(frenet_planner_EXPORT_TAGS)
list(APPEND frenet_planner_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
