set(_AMENT_PACKAGE_NAME "ar_tag_based_localizer")
set(ar_tag_based_localizer_VERSION "0.0.0")
set(ar_tag_based_localizer_MAINTAINER "Shintaro Sakoda <shintaro.sakoda@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(ar_tag_based_localizer_BUILD_DEPENDS "aruco" "cv_bridge" "diagnostic_msgs" "geometry_msgs" "image_transport" "rclcpp" "sensor_msgs" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs")
set(ar_tag_based_localizer_BUILDTOOL_DEPENDS "ament_cmake" "autoware_cmake")
set(ar_tag_based_localizer_BUILD_EXPORT_DEPENDS "aruco" "cv_bridge" "diagnostic_msgs" "geometry_msgs" "image_transport" "rclcpp" "sensor_msgs" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs")
set(ar_tag_based_localizer_BUILDTOOL_EXPORT_DEPENDS )
set(ar_tag_based_localizer_EXEC_DEPENDS "aruco" "cv_bridge" "diagnostic_msgs" "geometry_msgs" "image_transport" "rclcpp" "sensor_msgs" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs")
set(ar_tag_based_localizer_TEST_DEPENDS )
set(ar_tag_based_localizer_GROUP_DEPENDS )
set(ar_tag_based_localizer_MEMBER_OF_GROUPS )
set(ar_tag_based_localizer_DEPRECATED "")
set(ar_tag_based_localizer_EXPORT_TAGS)
list(APPEND ar_tag_based_localizer_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
