set(_AMENT_PACKAGE_NAME "boost_io_context")
set(boost_io_context_VERSION "1.2.0")
set(boost_io_context_MAINTAINER "Joshua Whitley <whitleysoftwareservices@gmail.com>")
set(boost_io_context_BUILD_DEPENDS "libboost-dev" "rclcpp" "std_msgs" "udp_msgs")
set(boost_io_context_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(boost_io_context_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "udp_msgs")
set(boost_io_context_BUILDTOOL_EXPORT_DEPENDS )
set(boost_io_context_EXEC_DEPENDS "rclcpp" "std_msgs" "udp_msgs")
set(boost_io_context_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(boost_io_context_GROUP_DEPENDS )
set(boost_io_context_MEMBER_OF_GROUPS )
set(boost_io_context_DEPRECATED "")
set(boost_io_context_EXPORT_TAGS)
list(APPEND boost_io_context_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
