set(_AMENT_PACKAGE_NAME "eagleye_fix2kml")
set(eagleye_fix2kml_VERSION "1.0.0")
set(eagleye_fix2kml_MAINTAINER "OsamuSekino <osamu.sekino@tier4.jp>")
set(eagleye_fix2kml_BUILD_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs")
set(eagleye_fix2kml_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_fix2kml_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs")
set(eagleye_fix2kml_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_fix2kml_EXEC_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs")
set(eagleye_fix2kml_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_fix2kml_GROUP_DEPENDS )
set(eagleye_fix2kml_MEMBER_OF_GROUPS )
set(eagleye_fix2kml_DEPRECATED "")
set(eagleye_fix2kml_EXPORT_TAGS)
list(APPEND eagleye_fix2kml_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
