set(_AMENT_PACKAGE_NAME "traffic_light_multi_camera_fusion")
set(traffic_light_multi_camera_fusion_VERSION "0.1.0")
set(traffic_light_multi_camera_fusion_MAINTAINER "Tao Zhong <tao.zhong@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(traffic_light_multi_camera_fusion_BUILD_DEPENDS "autoware_cmake" "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "sensor_msgs" "tier4_perception_msgs")
set(traffic_light_multi_camera_fusion_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(traffic_light_multi_camera_fusion_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "sensor_msgs" "tier4_perception_msgs")
set(traffic_light_multi_camera_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_multi_camera_fusion_EXEC_DEPENDS "autoware_auto_mapping_msgs" "autoware_perception_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "sensor_msgs" "tier4_perception_msgs")
set(traffic_light_multi_camera_fusion_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(traffic_light_multi_camera_fusion_GROUP_DEPENDS )
set(traffic_light_multi_camera_fusion_MEMBER_OF_GROUPS )
set(traffic_light_multi_camera_fusion_DEPRECATED "")
set(traffic_light_multi_camera_fusion_EXPORT_TAGS)
list(APPEND traffic_light_multi_camera_fusion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
