set(_AMENT_PACKAGE_NAME "nebula_hw_interfaces")
set(nebula_hw_interfaces_VERSION "0.1.0")
set(nebula_hw_interfaces_MAINTAINER "MAP IV <contact@map4.jp>")
set(nebula_hw_interfaces_BUILD_DEPENDS "libpcl-all-dev" "nebula_common" "pandar_msgs" "rclcpp" "sensor_msgs" "boost_tcp_driver" "boost_udp_driver" "velodyne_msgs")
set(nebula_hw_interfaces_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(nebula_hw_interfaces_BUILD_EXPORT_DEPENDS "libpcl-all-dev" "nebula_common" "pandar_msgs" "rclcpp" "sensor_msgs" "boost_tcp_driver" "boost_udp_driver" "velodyne_msgs")
set(nebula_hw_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_hw_interfaces_EXEC_DEPENDS "libpcl-all-dev" "nebula_common" "pandar_msgs" "rclcpp" "sensor_msgs" "boost_tcp_driver" "boost_udp_driver" "velodyne_msgs")
set(nebula_hw_interfaces_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto")
set(nebula_hw_interfaces_GROUP_DEPENDS )
set(nebula_hw_interfaces_MEMBER_OF_GROUPS )
set(nebula_hw_interfaces_DEPRECATED "")
set(nebula_hw_interfaces_EXPORT_TAGS)
list(APPEND nebula_hw_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
