set(_AMENT_PACKAGE_NAME "system_diagnostic_graph")
set(system_diagnostic_graph_VERSION "0.1.0")
set(system_diagnostic_graph_MAINTAINER "Takagi, Isamu <isamu.takagi@tier4.jp>")
set(system_diagnostic_graph_BUILD_DEPENDS "diagnostic_msgs" "rclcpp" "tier4_system_msgs" "yaml_cpp_vendor")
set(system_diagnostic_graph_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(system_diagnostic_graph_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "rclcpp" "tier4_system_msgs" "yaml_cpp_vendor")
set(system_diagnostic_graph_BUILDTOOL_EXPORT_DEPENDS )
set(system_diagnostic_graph_EXEC_DEPENDS "diagnostic_msgs" "rclcpp" "tier4_system_msgs" "yaml_cpp_vendor")
set(system_diagnostic_graph_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(system_diagnostic_graph_GROUP_DEPENDS )
set(system_diagnostic_graph_MEMBER_OF_GROUPS )
set(system_diagnostic_graph_DEPRECATED "")
set(system_diagnostic_graph_EXPORT_TAGS)
list(APPEND system_diagnostic_graph_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
