set(_AMENT_PACKAGE_NAME "heaphook")
set(heaphook_VERSION "0.1.1")
set(heaphook_MAINTAINER "sykwer <sykwer@gmail.com>")
set(heaphook_BUILD_DEPENDS "tlsf")
set(heaphook_BUILDTOOL_DEPENDS "ament_cmake")
set(heaphook_BUILD_EXPORT_DEPENDS "tlsf")
set(heaphook_BUILDTOOL_EXPORT_DEPENDS )
set(heaphook_EXEC_DEPENDS "tlsf")
set(heaphook_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(heaphook_GROUP_DEPENDS )
set(heaphook_MEMBER_OF_GROUPS )
set(heaphook_DEPRECATED "")
set(heaphook_EXPORT_TAGS)
list(APPEND heaphook_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
