set(_AMENT_PACKAGE_NAME "boost_tcp_driver")
set(boost_tcp_driver_VERSION "0.0.1")
set(boost_tcp_driver_MAINTAINER "Joshua Whitley <whitleysoftwareservices@gmail.com>")
set(boost_tcp_driver_BUILD_DEPENDS "boost" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle")
set(boost_tcp_driver_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(boost_tcp_driver_BUILD_EXPORT_DEPENDS "boost" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle")
set(boost_tcp_driver_BUILDTOOL_EXPORT_DEPENDS )
set(boost_tcp_driver_EXEC_DEPENDS "boost" "lifecycle_msgs" "rclcpp" "rclcpp_components" "rclcpp_lifecycle")
set(boost_tcp_driver_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common")
set(boost_tcp_driver_GROUP_DEPENDS )
set(boost_tcp_driver_MEMBER_OF_GROUPS )
set(boost_tcp_driver_DEPRECATED "")
set(boost_tcp_driver_EXPORT_TAGS)
list(APPEND boost_tcp_driver_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
