set(_AMENT_PACKAGE_NAME "behavior_velocity_intersection_module")
set(behavior_velocity_intersection_module_VERSION "0.1.0")
set(behavior_velocity_intersection_module_MAINTAINER "Mamoru Sobue <mamoru.sobue@tier4.jp>, Takayuki Murooka <takayuki.murooka@tier4.jp>, Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>, Kyoichi Sugahara <kyoichi.sugahara@tier4.jp>")
set(behavior_velocity_intersection_module_BUILD_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_perception_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_core" "interpolation" "lanelet2_extension" "libopencv-dev" "magic_enum" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "rtc_interface" "tf2_geometry_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_intersection_module_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(behavior_velocity_intersection_module_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_perception_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_core" "interpolation" "lanelet2_extension" "libopencv-dev" "magic_enum" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "rtc_interface" "tf2_geometry_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_intersection_module_BUILDTOOL_EXPORT_DEPENDS )
set(behavior_velocity_intersection_module_EXEC_DEPENDS "grid_map_rviz_plugin" "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "autoware_perception_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_core" "interpolation" "lanelet2_extension" "libopencv-dev" "magic_enum" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "rtc_interface" "tf2_geometry_msgs" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_intersection_module_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(behavior_velocity_intersection_module_GROUP_DEPENDS )
set(behavior_velocity_intersection_module_MEMBER_OF_GROUPS )
set(behavior_velocity_intersection_module_DEPRECATED "")
set(behavior_velocity_intersection_module_EXPORT_TAGS)
list(APPEND behavior_velocity_intersection_module_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
