set(_AMENT_PACKAGE_NAME "eagleye_can_velocity_converter")
set(eagleye_can_velocity_converter_VERSION "1.0.0")
set(eagleye_can_velocity_converter_MAINTAINER "Osamu Sekino <osamu.sekino@tier4.jp>")
set(eagleye_can_velocity_converter_BUILD_DEPENDS "can_msgs" "geometry_msgs" "rclcpp")
set(eagleye_can_velocity_converter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_can_velocity_converter_BUILD_EXPORT_DEPENDS "can_msgs" "geometry_msgs" "rclcpp")
set(eagleye_can_velocity_converter_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_can_velocity_converter_EXEC_DEPENDS "can_msgs" "geometry_msgs" "rclcpp")
set(eagleye_can_velocity_converter_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_can_velocity_converter_GROUP_DEPENDS )
set(eagleye_can_velocity_converter_MEMBER_OF_GROUPS )
set(eagleye_can_velocity_converter_DEPRECATED "")
set(eagleye_can_velocity_converter_EXPORT_TAGS)
list(APPEND eagleye_can_velocity_converter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
