set(_AMENT_PACKAGE_NAME "path_sampler")
set(path_sampler_VERSION "0.1.0")
set(path_sampler_MAINTAINER "Maxime CLEMENT <maxime.clement@tier4.jp>")
set(path_sampler_BUILD_DEPENDS "autoware_cmake" "autoware_auto_planning_msgs" "bezier_sampler" "frenet_planner" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(path_sampler_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(path_sampler_BUILD_EXPORT_DEPENDS "autoware_auto_planning_msgs" "bezier_sampler" "frenet_planner" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(path_sampler_BUILDTOOL_EXPORT_DEPENDS )
set(path_sampler_EXEC_DEPENDS "autoware_auto_planning_msgs" "bezier_sampler" "frenet_planner" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(path_sampler_TEST_DEPENDS "ament_cmake_ros" "ament_index_python" "ament_lint_auto" "autoware_lint_common" "autoware_testing" "fake_test_node")
set(path_sampler_GROUP_DEPENDS )
set(path_sampler_MEMBER_OF_GROUPS )
set(path_sampler_DEPRECATED "")
set(path_sampler_EXPORT_TAGS)
list(APPEND path_sampler_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
