set(_AMENT_PACKAGE_NAME "eagleye_navigation")
set(eagleye_navigation_VERSION "0.0.0")
set(eagleye_navigation_MAINTAINER "osamu.sekino <osamu.sekino@tier4.jp>")
set(eagleye_navigation_BUILD_DEPENDS "rclcpp" "geodesy" "eagleye_coordinate" "sensor_msgs" "nmea_msgs" "rtklib_msgs" "eagleye_msgs" "tf2_ros" "tf2_geometry_msgs" "yaml_cpp_vendor")
set(eagleye_navigation_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_navigation_BUILD_EXPORT_DEPENDS "rclcpp" "geodesy" "eagleye_coordinate" "sensor_msgs" "rtklib_msgs" "eagleye_msgs" "yaml_cpp_vendor")
set(eagleye_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_navigation_EXEC_DEPENDS "yaml_cpp_vendor")
set(eagleye_navigation_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_navigation_GROUP_DEPENDS )
set(eagleye_navigation_MEMBER_OF_GROUPS )
set(eagleye_navigation_DEPRECATED "")
set(eagleye_navigation_EXPORT_TAGS)
list(APPEND eagleye_navigation_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
