set(_AMENT_PACKAGE_NAME "autoware_auto_msgs_adapter")
set(autoware_auto_msgs_adapter_VERSION "1.0.0")
set(autoware_auto_msgs_adapter_MAINTAINER "M. Fatih Cırıt <mfc@leodrive.ai>, Takagi, Isamu <isamu.takagi@tier4.jp>")
set(autoware_auto_msgs_adapter_BUILD_DEPENDS "rosidl_default_generators" "autoware_auto_control_msgs" "autoware_auto_perception_msgs" "autoware_control_msgs" "autoware_perception_msgs" "rclcpp" "rclcpp_components")
set(autoware_auto_msgs_adapter_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(autoware_auto_msgs_adapter_BUILD_EXPORT_DEPENDS "autoware_auto_control_msgs" "autoware_auto_perception_msgs" "autoware_control_msgs" "autoware_perception_msgs" "rclcpp" "rclcpp_components")
set(autoware_auto_msgs_adapter_BUILDTOOL_EXPORT_DEPENDS )
set(autoware_auto_msgs_adapter_EXEC_DEPENDS "autoware_auto_control_msgs" "autoware_auto_perception_msgs" "autoware_control_msgs" "autoware_perception_msgs" "rclcpp" "rclcpp_components")
set(autoware_auto_msgs_adapter_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(autoware_auto_msgs_adapter_GROUP_DEPENDS )
set(autoware_auto_msgs_adapter_MEMBER_OF_GROUPS )
set(autoware_auto_msgs_adapter_DEPRECATED "")
set(autoware_auto_msgs_adapter_EXPORT_TAGS)
list(APPEND autoware_auto_msgs_adapter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
