set(_AMENT_PACKAGE_NAME "nebula_decoders")
set(nebula_decoders_VERSION "0.1.0")
set(nebula_decoders_MAINTAINER "MAP IV <contact@map4.jp>")
set(nebula_decoders_BUILD_DEPENDS "angles" "libpcl-all-dev" "nebula_common" "pandar_msgs" "pcl_conversions" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_decoders_BUILDTOOL_DEPENDS "ament_cmake_auto" "ros_environment")
set(nebula_decoders_BUILD_EXPORT_DEPENDS "angles" "libpcl-all-dev" "nebula_common" "pandar_msgs" "pcl_conversions" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_decoders_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_decoders_EXEC_DEPENDS "angles" "libpcl-all-dev" "nebula_common" "pandar_msgs" "pcl_conversions" "sensor_msgs" "velodyne_msgs" "yaml-cpp")
set(nebula_decoders_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto")
set(nebula_decoders_GROUP_DEPENDS )
set(nebula_decoders_MEMBER_OF_GROUPS )
set(nebula_decoders_DEPRECATED "")
set(nebula_decoders_EXPORT_TAGS)
list(APPEND nebula_decoders_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
