set(_AMENT_PACKAGE_NAME "mcity_planning")
set(mcity_planning_VERSION "0.1.0")
set(mcity_planning_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_planning_BUILD_DEPENDS "rclcpp" "rclcpp_components" "tf2_ros" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_planning_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_planning_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "tf2_ros" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_planning_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_planning_EXEC_DEPENDS "ros2launch" "rclcpp" "rclcpp_components" "tf2_ros" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_planning_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_planning_GROUP_DEPENDS )
set(mcity_planning_MEMBER_OF_GROUPS )
set(mcity_planning_DEPRECATED "")
set(mcity_planning_EXPORT_TAGS)
list(APPEND mcity_planning_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
