set(_AMENT_PACKAGE_NAME "traffic_light_occlusion_predictor")
set(traffic_light_occlusion_predictor_VERSION "0.1.0")
set(traffic_light_occlusion_predictor_MAINTAINER "Tao Zhong <tao.zhong@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(traffic_light_occlusion_predictor_BUILD_DEPENDS "autoware_cmake" "autoware_auto_geometry" "autoware_auto_mapping_msgs" "geometry_msgs" "image_geometry" "lanelet2_extension" "pcl_msgs" "perception_utils" "rclcpp" "rclcpp_components" "sensor_msgs" "tf2" "tf2_eigen" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "traffic_light_utils")
set(traffic_light_occlusion_predictor_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(traffic_light_occlusion_predictor_BUILD_EXPORT_DEPENDS "autoware_auto_geometry" "autoware_auto_mapping_msgs" "geometry_msgs" "image_geometry" "lanelet2_extension" "pcl_msgs" "perception_utils" "rclcpp" "rclcpp_components" "sensor_msgs" "tf2" "tf2_eigen" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "traffic_light_utils")
set(traffic_light_occlusion_predictor_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_occlusion_predictor_EXEC_DEPENDS "autoware_auto_geometry" "autoware_auto_mapping_msgs" "geometry_msgs" "image_geometry" "lanelet2_extension" "pcl_msgs" "perception_utils" "rclcpp" "rclcpp_components" "sensor_msgs" "tf2" "tf2_eigen" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "traffic_light_utils")
set(traffic_light_occlusion_predictor_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(traffic_light_occlusion_predictor_GROUP_DEPENDS )
set(traffic_light_occlusion_predictor_MEMBER_OF_GROUPS )
set(traffic_light_occlusion_predictor_DEPRECATED "")
set(traffic_light_occlusion_predictor_EXPORT_TAGS)
list(APPEND traffic_light_occlusion_predictor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
