set(_AMENT_PACKAGE_NAME "yabloc_monitor")
set(yabloc_monitor_VERSION "0.1.0")
set(yabloc_monitor_MAINTAINER "Kento Yabuuchi <kento.yabuuchi.2@tier4.jp>, Koji Minoda <koji.minoda@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(yabloc_monitor_BUILD_DEPENDS "diagnostic_updater" "geometry_msgs" "rclcpp")
set(yabloc_monitor_BUILDTOOL_DEPENDS "ament_cmake_ros" "autoware_cmake")
set(yabloc_monitor_BUILD_EXPORT_DEPENDS "diagnostic_updater" "geometry_msgs" "rclcpp")
set(yabloc_monitor_BUILDTOOL_EXPORT_DEPENDS )
set(yabloc_monitor_EXEC_DEPENDS "diagnostic_updater" "geometry_msgs" "rclcpp")
set(yabloc_monitor_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "autoware_lint_common")
set(yabloc_monitor_GROUP_DEPENDS )
set(yabloc_monitor_MEMBER_OF_GROUPS )
set(yabloc_monitor_DEPRECATED "")
set(yabloc_monitor_EXPORT_TAGS)
list(APPEND yabloc_monitor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
