set(_AMENT_PACKAGE_NAME "tier4_map_msgs")
set(tier4_map_msgs_VERSION "0.1.0")
set(tier4_map_msgs_MAINTAINER "Kah Hooi Tan <kahhooi.tan@tier4.jp>")
set(tier4_map_msgs_BUILD_DEPENDS "rosidl_default_generators" "geographic_msgs")
set(tier4_map_msgs_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(tier4_map_msgs_BUILD_EXPORT_DEPENDS "geographic_msgs")
set(tier4_map_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(tier4_map_msgs_EXEC_DEPENDS "rosidl_default_runtime" "geographic_msgs")
set(tier4_map_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(tier4_map_msgs_GROUP_DEPENDS )
set(tier4_map_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(tier4_map_msgs_DEPRECATED "")
set(tier4_map_msgs_EXPORT_TAGS)
list(APPEND tier4_map_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
