set(_AMENT_PACKAGE_NAME "planning_test_utils")
set(planning_test_utils_VERSION "0.1.0")
set(planning_test_utils_MAINTAINER "Kyoichi Sugahara <kyoichi.sugahara@tier4.jp>, Takamasa Horibe <takamasa.horibe@tier4.jp>")
set(planning_test_utils_BUILD_DEPENDS "autoware_auto_control_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_vehicle_msgs" "autoware_perception_msgs" "autoware_planning_msgs" "component_interface_specs" "component_interface_utils" "lanelet2_extension" "lanelet2_io" "nav_msgs" "rclcpp" "route_handler" "tf2_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "unique_identifier_msgs" "yaml_cpp_vendor")
set(planning_test_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(planning_test_utils_BUILD_EXPORT_DEPENDS "autoware_auto_control_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_vehicle_msgs" "autoware_perception_msgs" "autoware_planning_msgs" "component_interface_specs" "component_interface_utils" "lanelet2_extension" "lanelet2_io" "nav_msgs" "rclcpp" "route_handler" "tf2_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "unique_identifier_msgs" "yaml_cpp_vendor")
set(planning_test_utils_BUILDTOOL_EXPORT_DEPENDS )
set(planning_test_utils_EXEC_DEPENDS "autoware_auto_control_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_vehicle_msgs" "autoware_perception_msgs" "autoware_planning_msgs" "component_interface_specs" "component_interface_utils" "lanelet2_extension" "lanelet2_io" "nav_msgs" "rclcpp" "route_handler" "tf2_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "unique_identifier_msgs" "yaml_cpp_vendor")
set(planning_test_utils_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(planning_test_utils_GROUP_DEPENDS )
set(planning_test_utils_MEMBER_OF_GROUPS )
set(planning_test_utils_DEPRECATED "")
set(planning_test_utils_EXPORT_TAGS)
list(APPEND planning_test_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
