set(_AMENT_PACKAGE_NAME "eagleye_coordinate")
set(eagleye_coordinate_VERSION "0.0.0")
set(eagleye_coordinate_MAINTAINER "osamu.sekino <osamu.sekino@tier4.jp>")
set(eagleye_coordinate_BUILD_DEPENDS "rclcpp" "geodesy" "eigen" "geographic_info" "geographic_msgs" "geographiclib")
set(eagleye_coordinate_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_coordinate_BUILD_EXPORT_DEPENDS "rclcpp" "geodesy" "eigen" "geographic_info" "geographic_msgs" "geographiclib")
set(eagleye_coordinate_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_coordinate_EXEC_DEPENDS "eigen" "geographic_info" "geographic_msgs" "geographiclib")
set(eagleye_coordinate_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_coordinate_GROUP_DEPENDS )
set(eagleye_coordinate_MEMBER_OF_GROUPS )
set(eagleye_coordinate_DEPRECATED "")
set(eagleye_coordinate_EXPORT_TAGS)
list(APPEND eagleye_coordinate_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
