set(_AMENT_PACKAGE_NAME "behavior_velocity_planner_common")
set(behavior_velocity_planner_common_VERSION "0.1.0")
set(behavior_velocity_planner_common_MAINTAINER "Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>, Takagi, Isamu <isamu.takagi@tier4.jp>")
set(behavior_velocity_planner_common_BUILD_DEPENDS "autoware_adapi_v1_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "diagnostic_msgs" "eigen" "geometry_msgs" "interpolation" "lanelet2_extension" "libboost-dev" "motion_utils" "motion_velocity_smoother" "nav_msgs" "pcl_conversions" "rclcpp" "rclcpp_components" "route_handler" "rtc_interface" "sensor_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_planner_common_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake" "eigen3_cmake_module")
set(behavior_velocity_planner_common_BUILD_EXPORT_DEPENDS "autoware_adapi_v1_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "diagnostic_msgs" "eigen" "geometry_msgs" "interpolation" "lanelet2_extension" "libboost-dev" "motion_utils" "motion_velocity_smoother" "nav_msgs" "pcl_conversions" "rclcpp" "rclcpp_components" "route_handler" "rtc_interface" "sensor_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_planner_common_BUILDTOOL_EXPORT_DEPENDS )
set(behavior_velocity_planner_common_EXEC_DEPENDS "autoware_adapi_v1_msgs" "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_auto_tf2" "autoware_perception_msgs" "diagnostic_msgs" "eigen" "geometry_msgs" "interpolation" "lanelet2_extension" "libboost-dev" "motion_utils" "motion_velocity_smoother" "nav_msgs" "pcl_conversions" "rclcpp" "rclcpp_components" "route_handler" "rtc_interface" "sensor_msgs" "tf2" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros" "tier4_api_msgs" "tier4_autoware_utils" "tier4_planning_msgs" "tier4_v2x_msgs" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_planner_common_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(behavior_velocity_planner_common_GROUP_DEPENDS )
set(behavior_velocity_planner_common_MEMBER_OF_GROUPS )
set(behavior_velocity_planner_common_DEPRECATED "")
set(behavior_velocity_planner_common_EXPORT_TAGS)
list(APPEND behavior_velocity_planner_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
