set(_AMENT_PACKAGE_NAME "simple_object_merger")
set(simple_object_merger_VERSION "0.1.0")
set(simple_object_merger_MAINTAINER "Sathshi Tanaka <satoshi.tanaka@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>, Yoshi Ri <yoshi.ri@tier4.jp>")
set(simple_object_merger_BUILD_DEPENDS "autoware_cmake" "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(simple_object_merger_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(simple_object_merger_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(simple_object_merger_BUILDTOOL_EXPORT_DEPENDS )
set(simple_object_merger_EXEC_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tier4_autoware_utils")
set(simple_object_merger_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(simple_object_merger_GROUP_DEPENDS )
set(simple_object_merger_MEMBER_OF_GROUPS )
set(simple_object_merger_DEPRECATED "")
set(simple_object_merger_EXPORT_TAGS)
list(APPEND simple_object_merger_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
