set(_AMENT_PACKAGE_NAME "llh_converter")
set(llh_converter_VERSION "0.0.0")
set(llh_converter_MAINTAINER "Tomoya-Sato <tomoya.sato@tier4.jp>")
set(llh_converter_BUILD_DEPENDS "geographiclib")
set(llh_converter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(llh_converter_BUILD_EXPORT_DEPENDS "geographiclib")
set(llh_converter_BUILDTOOL_EXPORT_DEPENDS )
set(llh_converter_EXEC_DEPENDS "geographiclib")
set(llh_converter_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(llh_converter_GROUP_DEPENDS )
set(llh_converter_MEMBER_OF_GROUPS )
set(llh_converter_DEPRECATED "")
set(llh_converter_EXPORT_TAGS)
list(APPEND llh_converter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
