set(_AMENT_PACKAGE_NAME "object_recognition_utils")
set(object_recognition_utils_VERSION "0.1.0")
set(object_recognition_utils_MAINTAINER "Takayuki Murooka <takayuki.murooka@tier4.jp>, Satoshi Tanaka <satoshi.tanaka@tier4.jp>, Yusuke Muramatsu <yusuke.muramatsu@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(object_recognition_utils_BUILD_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "interpolation" "libboost-dev" "pcl_conversions" "pcl_ros" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tier4_autoware_utils")
set(object_recognition_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(object_recognition_utils_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "interpolation" "libboost-dev" "pcl_conversions" "pcl_ros" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tier4_autoware_utils")
set(object_recognition_utils_BUILDTOOL_EXPORT_DEPENDS )
set(object_recognition_utils_EXEC_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "interpolation" "libboost-dev" "pcl_conversions" "pcl_ros" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tier4_autoware_utils")
set(object_recognition_utils_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(object_recognition_utils_GROUP_DEPENDS )
set(object_recognition_utils_MEMBER_OF_GROUPS )
set(object_recognition_utils_DEPRECATED "")
set(object_recognition_utils_EXPORT_TAGS)
list(APPEND object_recognition_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
