set(_AMENT_PACKAGE_NAME "route_handler")
set(route_handler_VERSION "0.1.0")
set(route_handler_MAINTAINER "Fumiya Watanabe <fumiya.watanabe@tier4.jp>, Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>, Yutaka Shimizu <yutaka.shimizu@tier4.jp>, Kosuke Takeuchi <kosuke.takeuchi@tier4.jp>, Takayuki Murooka <takayuki.murooka@tier4.jp>, Mamoru Sobue <mamoru.sobue@tier4.jp>")
set(route_handler_BUILD_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_planning_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tf2_ros" "tier4_autoware_utils")
set(route_handler_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(route_handler_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_planning_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tf2_ros" "tier4_autoware_utils")
set(route_handler_BUILDTOOL_EXPORT_DEPENDS )
set(route_handler_EXEC_DEPENDS "autoware_auto_mapping_msgs" "autoware_auto_planning_msgs" "autoware_planning_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclcpp_components" "tf2_ros" "tier4_autoware_utils")
set(route_handler_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(route_handler_GROUP_DEPENDS )
set(route_handler_MEMBER_OF_GROUPS )
set(route_handler_DEPRECATED "")
set(route_handler_EXPORT_TAGS)
list(APPEND route_handler_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
