set(_AMENT_PACKAGE_NAME "obstacle_avoidance_planner")
set(obstacle_avoidance_planner_VERSION "0.1.0")
set(obstacle_avoidance_planner_MAINTAINER "Takayuki Murooka <takayuki.murooka@tier4.jp>, Kosuke Takeuchi <kosuke.takeuchi@tier4.jp>, Takamasa Horibe <takamasa.horibe@tier4.jp>")
set(obstacle_avoidance_planner_BUILD_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(obstacle_avoidance_planner_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(obstacle_avoidance_planner_BUILD_EXPORT_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(obstacle_avoidance_planner_BUILDTOOL_EXPORT_DEPENDS )
set(obstacle_avoidance_planner_EXEC_DEPENDS "autoware_auto_planning_msgs" "geometry_msgs" "interpolation" "motion_utils" "nav_msgs" "osqp_interface" "planning_test_utils" "rclcpp" "rclcpp_components" "std_msgs" "tf2_ros" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_planning_msgs" "vehicle_info_util" "visualization_msgs")
set(obstacle_avoidance_planner_TEST_DEPENDS "ament_cmake_ros" "ament_index_python" "ament_lint_auto" "autoware_lint_common" "autoware_testing" "fake_test_node")
set(obstacle_avoidance_planner_GROUP_DEPENDS )
set(obstacle_avoidance_planner_MEMBER_OF_GROUPS )
set(obstacle_avoidance_planner_DEPRECATED "")
set(obstacle_avoidance_planner_EXPORT_TAGS)
list(APPEND obstacle_avoidance_planner_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
