set(_AMENT_PACKAGE_NAME "mcity_realcar")
set(mcity_realcar_VERSION "0.1.0")
set(mcity_realcar_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_realcar_BUILD_DEPENDS "rclcpp" "rclcpp_components" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_realcar_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_realcar_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_realcar_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_realcar_EXEC_DEPENDS "ros2launch" "rclcpp" "rclcpp_components" "geometry_msgs" "mcity_msgs" "tier4_system_msgs" "autoware_adapi_v1_msgs" "autoware_auto_system_msgs" "autoware_auto_vehicle_msgs")
set(mcity_realcar_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_realcar_GROUP_DEPENDS )
set(mcity_realcar_MEMBER_OF_GROUPS )
set(mcity_realcar_DEPRECATED "")
set(mcity_realcar_EXPORT_TAGS)
list(APPEND mcity_realcar_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
