
float64 	timestamp
int16 		rail_cross_gate_enable_go
int16 		mcity_gate_enable_go

#car-door-openning
int16 		car_door_open
float64 	car_lon
float64 	car_lat
float64 	car_heading
float64 	car_speed
float64 	car_size_x
float64 	car_size_y
float64 	car_size_z


#dummy
int16 		dummy_moving
float64 	dummy_lon
float64 	dummy_lat
float64 	dummy_heading
float64 	dummy_speed
float64 	dummy_size_x
float64 	dummy_size_y
float64 	dummy_size_z