float64 timestamp
int64   RTK_timestamp_sec
int64   RTK_timestamp_nsec

int64   RTK_keep_count
int64   RTK_seq_num
int16   RTK_gps_status	
int16   RTK_gps_service

int64   Mobileye_keep_count
int16   Mobileye_lanes_num 

int64   DSRC_bsm_keep_count
int64 	DSRC_bsm_num
int64   DSRC_spat_keep_count
int64 	DSRC_spat_num

int64   Ibeo_points_keep_count
int64 	Ibeo_points_num
int64   Ibeo_objects_keep_count
int64 	Ibeo_objests_num

int64   Velodyne_points_keep_count
int64 	Velodyne_points_num
 
bool   throttle_enabled
bool   throttle_override
bool   throttle_driver
bool   throttle_timeout

bool   brake_enabled
bool   brake_override
bool   brake_driver
bool   brake_timeout

bool   steer_enabled
bool   steer_override
bool   steer_timeout

