set(_AMENT_PACKAGE_NAME "traffic_light_utils")
set(traffic_light_utils_VERSION "0.1.0")
set(traffic_light_utils_MAINTAINER "Mingyu Li <mingyu.li@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>")
set(traffic_light_utils_BUILD_DEPENDS "lanelet2_extension" "tier4_perception_msgs")
set(traffic_light_utils_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(traffic_light_utils_BUILD_EXPORT_DEPENDS "lanelet2_extension" "tier4_perception_msgs")
set(traffic_light_utils_BUILDTOOL_EXPORT_DEPENDS )
set(traffic_light_utils_EXEC_DEPENDS "lanelet2_extension" "tier4_perception_msgs")
set(traffic_light_utils_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(traffic_light_utils_GROUP_DEPENDS )
set(traffic_light_utils_MEMBER_OF_GROUPS )
set(traffic_light_utils_DEPRECATED "")
set(traffic_light_utils_EXPORT_TAGS)
list(APPEND traffic_light_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
