# CMake generated Testfile for 
# Source directory: /home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne
# Build directory: /home/mtl12345/autoware/build/nebula_tests/velodyne
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(velodyne_ros_decoder_test_main_vlp16 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/velodyne_ros_decoder_test_main_vlp16.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/velodyne_ros_decoder_test_main_vlp16.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/velodyne/velodyne_ros_decoder_test_main_vlp16" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/velodyne_ros_decoder_test_main_vlp16.gtest.xml")
set_tests_properties(velodyne_ros_decoder_test_main_vlp16 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/velodyne/velodyne_ros_decoder_test_main_vlp16" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/velodyne" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/CMakeLists.txt;7;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/CMakeLists.txt;0;")
add_test(velodyne_ros_decoder_test_main_vls128 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/velodyne_ros_decoder_test_main_vls128.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/velodyne_ros_decoder_test_main_vls128.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/velodyne/velodyne_ros_decoder_test_main_vls128" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/velodyne_ros_decoder_test_main_vls128.gtest.xml")
set_tests_properties(velodyne_ros_decoder_test_main_vls128 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/velodyne/velodyne_ros_decoder_test_main_vls128" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/velodyne" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/CMakeLists.txt;26;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/velodyne/CMakeLists.txt;0;")
