set(_AMENT_PACKAGE_NAME "eagleye_fix2pose")
set(eagleye_fix2pose_VERSION "1.0.0")
set(eagleye_fix2pose_MAINTAINER "OsamuSekino <osamu.sekino@tier4.jp>")
set(eagleye_fix2pose_BUILD_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs" "eagleye_navigation" "tf2_ros" "eagleye_coordinate" "llh_converter" "std_srvs" "tf2_geometry_msgs")
set(eagleye_fix2pose_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_fix2pose_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs" "eagleye_navigation" "tf2_ros" "eagleye_coordinate" "llh_converter" "std_srvs" "tf2_geometry_msgs")
set(eagleye_fix2pose_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_fix2pose_EXEC_DEPENDS "rclcpp" "rclpy" "std_msgs" "eagleye_msgs" "eagleye_navigation" "tf2_ros" "eagleye_coordinate" "llh_converter" "std_srvs" "tf2_geometry_msgs")
set(eagleye_fix2pose_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_fix2pose_GROUP_DEPENDS )
set(eagleye_fix2pose_MEMBER_OF_GROUPS )
set(eagleye_fix2pose_DEPRECATED "")
set(eagleye_fix2pose_EXPORT_TAGS)
list(APPEND eagleye_fix2pose_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
