set(_AMENT_PACKAGE_NAME "mcity_msgs")
set(mcity_msgs_VERSION "0.0.0")
set(mcity_msgs_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_msgs_BUILD_DEPENDS "rclcpp" "std_msgs" "rosidl_default_generators")
set(mcity_msgs_BUILDTOOL_DEPENDS "ament_cmake")
set(mcity_msgs_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "rosidl_default_generators")
set(mcity_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_msgs_EXEC_DEPENDS "rclcpp" "std_msgs" "rosidl_default_generators")
set(mcity_msgs_TEST_DEPENDS )
set(mcity_msgs_GROUP_DEPENDS )
set(mcity_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(mcity_msgs_DEPRECATED "")
set(mcity_msgs_EXPORT_TAGS)
list(APPEND mcity_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
