set(_AMENT_PACKAGE_NAME "mcity_control")
set(mcity_control_VERSION "1.0.0")
set(mcity_control_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_control_BUILD_DEPENDS "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "mcity_msgs" "geometry_msgs")
set(mcity_control_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(mcity_control_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "mcity_msgs" "geometry_msgs")
set(mcity_control_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_control_EXEC_DEPENDS "ros2launch" "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "mcity_msgs" "geometry_msgs")
set(mcity_control_TEST_DEPENDS "ament_lint_auto")
set(mcity_control_GROUP_DEPENDS )
set(mcity_control_MEMBER_OF_GROUPS )
set(mcity_control_DEPRECATED "")
set(mcity_control_EXPORT_TAGS)
list(APPEND mcity_control_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
