set(_AMENT_PACKAGE_NAME "nebula_sensor_driver")
set(nebula_sensor_driver_VERSION "0.0.1")
set(nebula_sensor_driver_MAINTAINER "MAP IV <contact@map4.jp>, MAP IV <contact@tier4.jp>")
set(nebula_sensor_driver_BUILD_DEPENDS )
set(nebula_sensor_driver_BUILDTOOL_DEPENDS "ament_cmake")
set(nebula_sensor_driver_BUILD_EXPORT_DEPENDS )
set(nebula_sensor_driver_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_sensor_driver_EXEC_DEPENDS "nebula_common" "nebula_decoders" "nebula_examples" "nebula_examples" "nebula_hw_interfaces" "nebula_ros" "nebula_tests" "pandar_msgs" "velodyne_msgs")
set(nebula_sensor_driver_TEST_DEPENDS )
set(nebula_sensor_driver_GROUP_DEPENDS )
set(nebula_sensor_driver_MEMBER_OF_GROUPS )
set(nebula_sensor_driver_DEPRECATED "")
set(nebula_sensor_driver_EXPORT_TAGS)
list(APPEND nebula_sensor_driver_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
