set(_AMENT_PACKAGE_NAME "mcity_voices")
set(mcity_voices_VERSION "0.1.0")
set(mcity_voices_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_voices_BUILD_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_voices_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_voices_BUILD_EXPORT_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_voices_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_voices_EXEC_DEPENDS "ros2launch" "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_voices_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_voices_GROUP_DEPENDS )
set(mcity_voices_MEMBER_OF_GROUPS )
set(mcity_voices_DEPRECATED "")
set(mcity_voices_EXPORT_TAGS)
list(APPEND mcity_voices_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
