set(_AMENT_PACKAGE_NAME "yabloc_common")
set(yabloc_common_VERSION "0.1.0")
set(yabloc_common_MAINTAINER "Kento Yabuuchi <kento.yabuuchi.2@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(yabloc_common_BUILD_DEPENDS "autoware_auto_mapping_msgs" "cv_bridge" "geographiclib" "geometry_msgs" "lanelet2_core" "lanelet2_extension" "lanelet2_io" "libgoogle-glog-dev" "pcl_conversions" "rcl_interfaces" "rclcpp" "rclcpp_components" "sensor_msgs" "signal_processing" "sophus" "std_msgs" "tf2_ros" "ublox_msgs" "visualization_msgs")
set(yabloc_common_BUILDTOOL_DEPENDS "ament_cmake_ros" "autoware_cmake" "rosidl_default_generators")
set(yabloc_common_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "cv_bridge" "geographiclib" "geometry_msgs" "lanelet2_core" "lanelet2_extension" "lanelet2_io" "libgoogle-glog-dev" "pcl_conversions" "rcl_interfaces" "rclcpp" "rclcpp_components" "sensor_msgs" "signal_processing" "sophus" "std_msgs" "tf2_ros" "ublox_msgs" "visualization_msgs")
set(yabloc_common_BUILDTOOL_EXPORT_DEPENDS )
set(yabloc_common_EXEC_DEPENDS "rosidl_default_runtime" "autoware_auto_mapping_msgs" "cv_bridge" "geographiclib" "geometry_msgs" "lanelet2_core" "lanelet2_extension" "lanelet2_io" "libgoogle-glog-dev" "pcl_conversions" "rcl_interfaces" "rclcpp" "rclcpp_components" "sensor_msgs" "signal_processing" "sophus" "std_msgs" "tf2_ros" "ublox_msgs" "visualization_msgs")
set(yabloc_common_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(yabloc_common_GROUP_DEPENDS )
set(yabloc_common_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(yabloc_common_DEPRECATED "")
set(yabloc_common_EXPORT_TAGS)
list(APPEND yabloc_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
