# CMake generated Testfile for 
# Source directory: /home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai
# Build directory: /home/mtl12345/autoware/build/nebula_tests/hesai
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(hesai_ros_decoder_test_main_at128 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_at128.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_at128.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_at128" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_at128.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_at128 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_at128" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;7;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
add_test(hesai_ros_decoder_test_main_xt32m "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_xt32m.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_xt32m.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_xt32m" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_xt32m.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_xt32m PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_xt32m" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;31;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
add_test(hesai_ros_decoder_test_main_40p "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_40p.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_40p.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_40p" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_40p.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_40p PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_40p" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;56;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
add_test(hesai_ros_decoder_test_main_64 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_64.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_64.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_64" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_64.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_64 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_64" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;81;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
add_test(hesai_ros_decoder_test_main_qt64 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_qt64.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_qt64.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_qt64" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_qt64.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_qt64 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_qt64" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;106;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
add_test(hesai_ros_decoder_test_main_xt32 "/usr/bin/python3.10" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_xt32.gtest.xml" "--package-name" "nebula_tests" "--output-file" "/home/mtl12345/autoware/build/nebula_tests/ament_cmake_gtest/hesai_ros_decoder_test_main_xt32.txt" "--command" "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_xt32" "--gtest_output=xml:/home/mtl12345/autoware/build/nebula_tests/test_results/nebula_tests/hesai_ros_decoder_test_main_xt32.gtest.xml")
set_tests_properties(hesai_ros_decoder_test_main_xt32 PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/mtl12345/autoware/build/nebula_tests/hesai/hesai_ros_decoder_test_main_xt32" TIMEOUT "60" WORKING_DIRECTORY "/home/mtl12345/autoware/build/nebula_tests/hesai" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;130;ament_add_gtest;/home/mtl12345/autoware/src/sensor_component/external/nebula/nebula_tests/hesai/CMakeLists.txt;0;")
subdirs("../gtest")
