set(_AMENT_PACKAGE_NAME "eagleye_rt")
set(eagleye_rt_VERSION "0.0.0")
set(eagleye_rt_MAINTAINER "Osamu Sekino <osamu.sekino@tier4.jp>")
set(eagleye_rt_BUILD_DEPENDS "yaml_cpp_vendor" "tf2_eigen" "rclcpp" "std_msgs" "geometry_msgs" "geographic_msgs" "geodesy" "sensor_msgs" "nmea_msgs" "rtklib_msgs" "eagleye_msgs" "eagleye_coordinate" "eagleye_navigation" "diagnostic_updater" "tf2" "tf2_ros" "tf2_geometry_msgs" "tf2_sensor_msgs" "ublox_msgs")
set(eagleye_rt_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_rt_BUILD_EXPORT_DEPENDS "yaml_cpp_vendor" "tf2_eigen" "rclcpp" "std_msgs" "geometry_msgs" "geographic_msgs" "geodesy" "sensor_msgs" "nmea_msgs" "rtklib_msgs" "eagleye_msgs" "eagleye_coordinate" "eagleye_navigation" "diagnostic_updater" "tf2" "tf2_ros" "tf2_geometry_msgs" "tf2_sensor_msgs" "ublox_msgs")
set(eagleye_rt_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_rt_EXEC_DEPENDS "yaml_cpp_vendor" "tf2_eigen" "rclcpp" "std_msgs" "geometry_msgs" "geographic_msgs" "geodesy" "sensor_msgs" "nmea_msgs" "rtklib_msgs" "eagleye_msgs" "eagleye_coordinate" "eagleye_navigation" "diagnostic_updater" "tf2" "tf2_ros" "tf2_geometry_msgs" "tf2_sensor_msgs" "ublox_msgs")
set(eagleye_rt_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_rt_GROUP_DEPENDS )
set(eagleye_rt_MEMBER_OF_GROUPS )
set(eagleye_rt_DEPRECATED "")
set(eagleye_rt_EXPORT_TAGS)
list(APPEND eagleye_rt_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
