set(_AMENT_PACKAGE_NAME "radar_object_clustering")
set(radar_object_clustering_VERSION "0.1.0")
set(radar_object_clustering_MAINTAINER "Sathshi Tanaka <satoshi.tanaka@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>, Yoshi Ri <yoshi.ri@tier4.jp>")
set(radar_object_clustering_BUILD_DEPENDS "autoware_cmake" "autoware_auto_perception_msgs" "geometry_msgs" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_object_clustering_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(radar_object_clustering_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_object_clustering_BUILDTOOL_EXPORT_DEPENDS )
set(radar_object_clustering_EXEC_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_object_clustering_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(radar_object_clustering_GROUP_DEPENDS )
set(radar_object_clustering_MEMBER_OF_GROUPS )
set(radar_object_clustering_DEPRECATED "")
set(radar_object_clustering_EXPORT_TAGS)
list(APPEND radar_object_clustering_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
