set(_AMENT_PACKAGE_NAME "yabloc_pose_initializer")
set(yabloc_pose_initializer_VERSION "0.0.0")
set(yabloc_pose_initializer_MAINTAINER "Kento Yabuuchi <kento.yabuuchi.2@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(yabloc_pose_initializer_BUILD_DEPENDS "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclpy" "sensor_msgs" "std_msgs" "std_srvs" "tf2" "tier4_localization_msgs" "visualization_msgs" "yabloc_common")
set(yabloc_pose_initializer_BUILDTOOL_DEPENDS "ament_cmake_ros" "autoware_cmake" "rosidl_default_generators")
set(yabloc_pose_initializer_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclpy" "sensor_msgs" "std_msgs" "std_srvs" "tf2" "tier4_localization_msgs" "visualization_msgs" "yabloc_common")
set(yabloc_pose_initializer_BUILDTOOL_EXPORT_DEPENDS )
set(yabloc_pose_initializer_EXEC_DEPENDS "rosidl_default_runtime" "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "rclcpp" "rclpy" "sensor_msgs" "std_msgs" "std_srvs" "tf2" "tier4_localization_msgs" "visualization_msgs" "yabloc_common")
set(yabloc_pose_initializer_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(yabloc_pose_initializer_GROUP_DEPENDS )
set(yabloc_pose_initializer_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(yabloc_pose_initializer_DEPRECATED "")
set(yabloc_pose_initializer_EXPORT_TAGS)
list(APPEND yabloc_pose_initializer_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
