set(_AMENT_PACKAGE_NAME "radar_object_tracker")
set(radar_object_tracker_VERSION "0.0.0")
set(radar_object_tracker_MAINTAINER "Yoshi Ri <yoshi.ri@tier4.jp>, Yukihiro Saito <yukihiro.saito@tier4.jp>, Satoshi Tanaka <satoshi.tanaka@tier4.jp>")
set(radar_object_tracker_BUILD_DEPENDS "autoware_auto_perception_msgs" "eigen" "kalman_filter" "lanelet2_extension" "mussp" "nlohmann-json-dev" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "unique_identifier_msgs" "yaml-cpp")
set(radar_object_tracker_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake" "eigen3_cmake_module")
set(radar_object_tracker_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "eigen" "kalman_filter" "lanelet2_extension" "mussp" "nlohmann-json-dev" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "unique_identifier_msgs" "yaml-cpp")
set(radar_object_tracker_BUILDTOOL_EXPORT_DEPENDS )
set(radar_object_tracker_EXEC_DEPENDS "autoware_auto_perception_msgs" "eigen" "kalman_filter" "lanelet2_extension" "mussp" "nlohmann-json-dev" "object_recognition_utils" "rclcpp" "rclcpp_components" "tf2" "tf2_ros" "tier4_autoware_utils" "tier4_perception_msgs" "unique_identifier_msgs" "yaml-cpp")
set(radar_object_tracker_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(radar_object_tracker_GROUP_DEPENDS )
set(radar_object_tracker_MEMBER_OF_GROUPS )
set(radar_object_tracker_DEPRECATED "")
set(radar_object_tracker_EXPORT_TAGS)
list(APPEND radar_object_tracker_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
