set(_AMENT_PACKAGE_NAME "mcity_mr")
set(mcity_mr_VERSION "0.1.0")
set(mcity_mr_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_mr_BUILD_DEPENDS "nav_msgs" "std_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "autoware_perception_msgs" "autoware_auto_perception_msgs")
set(mcity_mr_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_mr_BUILD_EXPORT_DEPENDS "nav_msgs" "std_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "autoware_perception_msgs" "autoware_auto_perception_msgs")
set(mcity_mr_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_mr_EXEC_DEPENDS "ros2launch" "nav_msgs" "std_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "autoware_perception_msgs" "autoware_auto_perception_msgs")
set(mcity_mr_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_mr_GROUP_DEPENDS )
set(mcity_mr_MEMBER_OF_GROUPS )
set(mcity_mr_DEPRECATED "")
set(mcity_mr_EXPORT_TAGS)
list(APPEND mcity_mr_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
