set(_AMENT_PACKAGE_NAME "rtklib_bridge")
set(rtklib_bridge_VERSION "0.0.0")
set(rtklib_bridge_MAINTAINER "megken <megken@todo.todo>")
set(rtklib_bridge_BUILD_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "rtklib_msgs" "common_interfaces")
set(rtklib_bridge_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(rtklib_bridge_BUILD_EXPORT_DEPENDS )
set(rtklib_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(rtklib_bridge_EXEC_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "rtklib_msgs" "common_interfaces")
set(rtklib_bridge_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rtklib_bridge_GROUP_DEPENDS )
set(rtklib_bridge_MEMBER_OF_GROUPS )
set(rtklib_bridge_DEPRECATED "")
set(rtklib_bridge_EXPORT_TAGS)
list(APPEND rtklib_bridge_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
