set(_AMENT_PACKAGE_NAME "behavior_velocity_occlusion_spot_module")
set(behavior_velocity_occlusion_spot_module_VERSION "0.1.0")
set(behavior_velocity_occlusion_spot_module_MAINTAINER "Taiki Tanaka <taiki.tanaka@tier4.jp>, Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>")
set(behavior_velocity_occlusion_spot_module_BUILD_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_ros" "grid_map_utils" "interpolation" "lanelet2_extension" "libboost-dev" "libopencv-dev" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_occlusion_spot_module_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(behavior_velocity_occlusion_spot_module_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_ros" "grid_map_utils" "interpolation" "lanelet2_extension" "libboost-dev" "libopencv-dev" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_occlusion_spot_module_BUILDTOOL_EXPORT_DEPENDS )
set(behavior_velocity_occlusion_spot_module_EXEC_DEPENDS "autoware_auto_perception_msgs" "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "geometry_msgs" "grid_map_ros" "grid_map_utils" "interpolation" "lanelet2_extension" "libboost-dev" "libopencv-dev" "motion_utils" "nav_msgs" "pluginlib" "rclcpp" "route_handler" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils" "vehicle_info_util" "visualization_msgs")
set(behavior_velocity_occlusion_spot_module_TEST_DEPENDS "ament_cmake_ros" "ament_lint_auto" "autoware_lint_common")
set(behavior_velocity_occlusion_spot_module_GROUP_DEPENDS )
set(behavior_velocity_occlusion_spot_module_MEMBER_OF_GROUPS )
set(behavior_velocity_occlusion_spot_module_DEPRECATED "")
set(behavior_velocity_occlusion_spot_module_EXPORT_TAGS)
list(APPEND behavior_velocity_occlusion_spot_module_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
