set(_AMENT_PACKAGE_NAME "tier4_target_object_type_rviz_plugin")
set(tier4_target_object_type_rviz_plugin_VERSION "0.0.1")
set(tier4_target_object_type_rviz_plugin_MAINTAINER "Takamasa Horibe <takamasa.horibe@tier4.jp>")
set(tier4_target_object_type_rviz_plugin_BUILD_DEPENDS "cv_bridge" "libqt5-core" "libqt5-gui" "libqt5-widgets" "qtbase5-dev" "rclcpp" "rviz_common" "rviz_rendering")
set(tier4_target_object_type_rviz_plugin_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(tier4_target_object_type_rviz_plugin_BUILD_EXPORT_DEPENDS "cv_bridge" "libqt5-core" "libqt5-gui" "libqt5-widgets" "qtbase5-dev" "rclcpp" "rviz_common" "rviz_rendering")
set(tier4_target_object_type_rviz_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(tier4_target_object_type_rviz_plugin_EXEC_DEPENDS "cv_bridge" "libqt5-core" "libqt5-gui" "libqt5-widgets" "qtbase5-dev" "rclcpp" "rviz_common" "rviz_rendering")
set(tier4_target_object_type_rviz_plugin_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(tier4_target_object_type_rviz_plugin_GROUP_DEPENDS )
set(tier4_target_object_type_rviz_plugin_MEMBER_OF_GROUPS )
set(tier4_target_object_type_rviz_plugin_DEPRECATED "")
set(tier4_target_object_type_rviz_plugin_EXPORT_TAGS)
list(APPEND tier4_target_object_type_rviz_plugin_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND tier4_target_object_type_rviz_plugin_EXPORT_TAGS "<rviz plugin=\"plugins/plugin_description.xml\"/>")
