set(_AMENT_PACKAGE_NAME "mcity_uw")
set(mcity_uw_VERSION "0.1.0")
set(mcity_uw_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_uw_BUILD_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_uw_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_uw_BUILD_EXPORT_DEPENDS "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_uw_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_uw_EXEC_DEPENDS "ros2launch" "tf2_ros" "nav_msgs" "std_msgs" "mcity_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components" "autoware_adapi_v1_msgs" "autoware_perception_msgs" "autoware_auto_system_msgs" "autoware_auto_perception_msgs" "tier4_system_msgs" "dummy_perception_publisher" "autoware_auto_vehicle_msgs" "autoware_auto_control_msgs")
set(mcity_uw_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_uw_GROUP_DEPENDS )
set(mcity_uw_MEMBER_OF_GROUPS )
set(mcity_uw_DEPRECATED "")
set(mcity_uw_EXPORT_TAGS)
list(APPEND mcity_uw_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
