set(_AMENT_PACKAGE_NAME "yabloc_image_processing")
set(yabloc_image_processing_VERSION "0.0.0")
set(yabloc_image_processing_MAINTAINER "Kento Yabuuchi <kento.yabuuchi.2@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(yabloc_image_processing_BUILD_DEPENDS "cv_bridge" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "sophus" "std_msgs" "tf2" "tf2_ros" "tier4_autoware_utils" "visualization_msgs" "yabloc_common")
set(yabloc_image_processing_BUILDTOOL_DEPENDS "ament_cmake" "autoware_cmake")
set(yabloc_image_processing_BUILD_EXPORT_DEPENDS "cv_bridge" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "sophus" "std_msgs" "tf2" "tf2_ros" "tier4_autoware_utils" "visualization_msgs" "yabloc_common")
set(yabloc_image_processing_BUILDTOOL_EXPORT_DEPENDS )
set(yabloc_image_processing_EXEC_DEPENDS "cv_bridge" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "sophus" "std_msgs" "tf2" "tf2_ros" "tier4_autoware_utils" "visualization_msgs" "yabloc_common")
set(yabloc_image_processing_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(yabloc_image_processing_GROUP_DEPENDS )
set(yabloc_image_processing_MEMBER_OF_GROUPS )
set(yabloc_image_processing_DEPRECATED "")
set(yabloc_image_processing_EXPORT_TAGS)
list(APPEND yabloc_image_processing_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
