set(_AMENT_PACKAGE_NAME "nebula_common")
set(nebula_common_VERSION "0.1.0")
set(nebula_common_MAINTAINER "MAP IV <contact@map4.jp>")
set(nebula_common_BUILD_DEPENDS "libpcl-all-dev" "pcl_conversions" "yaml-cpp")
set(nebula_common_BUILDTOOL_DEPENDS "ament_cmake_auto" "ros_environment")
set(nebula_common_BUILD_EXPORT_DEPENDS "libpcl-all-dev" "pcl_conversions" "yaml-cpp")
set(nebula_common_BUILDTOOL_EXPORT_DEPENDS )
set(nebula_common_EXEC_DEPENDS "libpcl-all-dev" "pcl_conversions" "yaml-cpp")
set(nebula_common_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto")
set(nebula_common_GROUP_DEPENDS )
set(nebula_common_MEMBER_OF_GROUPS )
set(nebula_common_DEPRECATED "")
set(nebula_common_EXPORT_TAGS)
list(APPEND nebula_common_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
