set(_AMENT_PACKAGE_NAME "behavior_velocity_speed_bump_module")
set(behavior_velocity_speed_bump_module_VERSION "0.1.0")
set(behavior_velocity_speed_bump_module_MAINTAINER "Tomoya Kimura <tomoya.kimura@tier4.jp>, Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>, Mehmet Dogru <mdogru@leodrive.ai>")
set(behavior_velocity_speed_bump_module_BUILD_DEPENDS "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tf2" "tier4_autoware_utils" "visualization_msgs")
set(behavior_velocity_speed_bump_module_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake" "eigen3_cmake_module")
set(behavior_velocity_speed_bump_module_BUILD_EXPORT_DEPENDS "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tf2" "tier4_autoware_utils" "visualization_msgs")
set(behavior_velocity_speed_bump_module_BUILDTOOL_EXPORT_DEPENDS )
set(behavior_velocity_speed_bump_module_EXEC_DEPENDS "autoware_auto_planning_msgs" "behavior_velocity_planner_common" "eigen" "geometry_msgs" "lanelet2_extension" "libboost-dev" "motion_utils" "pluginlib" "rclcpp" "route_handler" "sensor_msgs" "tf2" "tier4_autoware_utils" "visualization_msgs")
set(behavior_velocity_speed_bump_module_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(behavior_velocity_speed_bump_module_GROUP_DEPENDS )
set(behavior_velocity_speed_bump_module_MEMBER_OF_GROUPS )
set(behavior_velocity_speed_bump_module_DEPRECATED "")
set(behavior_velocity_speed_bump_module_EXPORT_TAGS)
list(APPEND behavior_velocity_speed_bump_module_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
