set(_AMENT_PACKAGE_NAME "map_projection_loader")
set(map_projection_loader_VERSION "0.1.0")
set(map_projection_loader_MAINTAINER "Koji Minoda <koji.minoda@tier4.jp>, Yamato Ando <yamato.ando@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(map_projection_loader_BUILD_DEPENDS "component_interface_specs" "component_interface_utils" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_map_msgs" "yaml-cpp")
set(map_projection_loader_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(map_projection_loader_BUILD_EXPORT_DEPENDS "component_interface_specs" "component_interface_utils" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_map_msgs" "yaml-cpp")
set(map_projection_loader_BUILDTOOL_EXPORT_DEPENDS )
set(map_projection_loader_EXEC_DEPENDS "component_interface_specs" "component_interface_utils" "lanelet2_extension" "rclcpp" "rclcpp_components" "tier4_map_msgs" "yaml-cpp")
set(map_projection_loader_TEST_DEPENDS "ament_cmake_gmock" "ament_cmake_gtest" "ament_lint_auto" "autoware_lint_common" "ros_testing")
set(map_projection_loader_GROUP_DEPENDS )
set(map_projection_loader_MEMBER_OF_GROUPS )
set(map_projection_loader_DEPRECATED "")
set(map_projection_loader_EXPORT_TAGS)
list(APPEND map_projection_loader_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
