set(_AMENT_PACKAGE_NAME "eagleye_msgs")
set(eagleye_msgs_VERSION "0.0.0")
set(eagleye_msgs_MAINTAINER "osamu.sekino <osamu.sekino@tier4.jp>")
set(eagleye_msgs_BUILD_DEPENDS "rosidl_default_generators" "rclcpp" "geometry_msgs" "sensor_msgs" "rtklib_msgs")
set(eagleye_msgs_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_msgs_BUILD_EXPORT_DEPENDS "rclcpp" "geometry_msgs" "sensor_msgs" "rtklib_msgs")
set(eagleye_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_msgs_EXEC_DEPENDS "rosidl_default_runtime")
set(eagleye_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_msgs_GROUP_DEPENDS )
set(eagleye_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(eagleye_msgs_DEPRECATED "")
set(eagleye_msgs_EXPORT_TAGS)
list(APPEND eagleye_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
