set(_AMENT_PACKAGE_NAME "mcity_carla")
set(mcity_carla_VERSION "0.1.0")
set(mcity_carla_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_carla_BUILD_DEPENDS "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components")
set(mcity_carla_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_carla_BUILD_EXPORT_DEPENDS "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components")
set(mcity_carla_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_carla_EXEC_DEPENDS "ros2launch" "nav_msgs" "std_msgs" "geometry_msgs" "sensor_msgs" "rclcpp" "rclcpp_components")
set(mcity_carla_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(mcity_carla_GROUP_DEPENDS )
set(mcity_carla_MEMBER_OF_GROUPS )
set(mcity_carla_DEPRECATED "")
set(mcity_carla_EXPORT_TAGS)
list(APPEND mcity_carla_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
