set(_AMENT_PACKAGE_NAME "eagleye_tf")
set(eagleye_tf_VERSION "0.0.0")
set(eagleye_tf_MAINTAINER "Osamu Sekino <osamu.sekino@tier4.jp>")
set(eagleye_tf_BUILD_DEPENDS )
set(eagleye_tf_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_tf_BUILD_EXPORT_DEPENDS )
set(eagleye_tf_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_tf_EXEC_DEPENDS )
set(eagleye_tf_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_tf_GROUP_DEPENDS )
set(eagleye_tf_MEMBER_OF_GROUPS )
set(eagleye_tf_DEPRECATED "")
set(eagleye_tf_EXPORT_TAGS)
list(APPEND eagleye_tf_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
