set(_AMENT_PACKAGE_NAME "system_diagnostic_monitor")
set(system_diagnostic_monitor_VERSION "0.1.0")
set(system_diagnostic_monitor_MAINTAINER "Takagi, Isamu <isamu.takagi@tier4.jp>")
set(system_diagnostic_monitor_BUILD_DEPENDS "system_diagnostic_graph")
set(system_diagnostic_monitor_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(system_diagnostic_monitor_BUILD_EXPORT_DEPENDS "system_diagnostic_graph")
set(system_diagnostic_monitor_BUILDTOOL_EXPORT_DEPENDS )
set(system_diagnostic_monitor_EXEC_DEPENDS "autoware_adapi_v1_msgs" "system_diagnostic_graph")
set(system_diagnostic_monitor_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(system_diagnostic_monitor_GROUP_DEPENDS )
set(system_diagnostic_monitor_MEMBER_OF_GROUPS )
set(system_diagnostic_monitor_DEPRECATED "")
set(system_diagnostic_monitor_EXPORT_TAGS)
list(APPEND system_diagnostic_monitor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
