set(_AMENT_PACKAGE_NAME "glog_component")
set(glog_component_VERSION "0.1.0")
set(glog_component_MAINTAINER "Takamasa Horibe <takamasa.horibe@tier4.jp>")
set(glog_component_BUILD_DEPENDS "libgoogle-glog-dev" "rclcpp" "rclcpp_components")
set(glog_component_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_auto" "autoware_cmake")
set(glog_component_BUILD_EXPORT_DEPENDS "libgoogle-glog-dev" "rclcpp" "rclcpp_components")
set(glog_component_BUILDTOOL_EXPORT_DEPENDS )
set(glog_component_EXEC_DEPENDS "libgoogle-glog-dev" "rclcpp" "rclcpp_components")
set(glog_component_TEST_DEPENDS )
set(glog_component_GROUP_DEPENDS )
set(glog_component_MEMBER_OF_GROUPS )
set(glog_component_DEPRECATED "")
set(glog_component_EXPORT_TAGS)
list(APPEND glog_component_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
