set(_AMENT_PACKAGE_NAME "cluster_merger")
set(cluster_merger_VERSION "0.1.0")
set(cluster_merger_MAINTAINER "Yukihiro Saito <yukihiro.saito@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>, autoware <dai.nguyen@tier4.jp>")
set(cluster_merger_BUILD_DEPENDS "autoware_cmake" "geometry_msgs" "message_filters" "object_recognition_utils" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "tier4_perception_msgs")
set(cluster_merger_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(cluster_merger_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_filters" "object_recognition_utils" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "tier4_perception_msgs")
set(cluster_merger_BUILDTOOL_EXPORT_DEPENDS )
set(cluster_merger_EXEC_DEPENDS "geometry_msgs" "message_filters" "object_recognition_utils" "rclcpp" "rclcpp_components" "tier4_autoware_utils" "tier4_perception_msgs")
set(cluster_merger_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(cluster_merger_GROUP_DEPENDS )
set(cluster_merger_MEMBER_OF_GROUPS )
set(cluster_merger_DEPRECATED "")
set(cluster_merger_EXPORT_TAGS)
list(APPEND cluster_merger_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
