DBW_TEST:
  ros__parameters:
    # brake parameters
    brake_pedal_cmd: 0.1
    brake_pedal_cmd_type: 2
    brake_enable: False
    brake_clear: False
    brake_ignore: False
    
    # throttle parameters
    throttle_pedal_cmd: 0.1
    throttle_pedal_cmd_type: 2
    throttle_enable: False
    throttle_clear: False
    throttle_ignore: False
    
    # steering parameters
    steering_wheel_angle_cmd: 0.0
    steering_wheel_angle_velocity: 0.0
    steering_wheel_torque_cmd: 0.0
    steering_cmd_type: 0
    steering_enable: False
    steering_clear: False
    steering_ignore: False
    steering_quiet: False
    steering_alert: False

    # gear parameters
    gear_cmd: 0
    gear_clear: True
