set(_AMENT_PACKAGE_NAME "radar_crossing_objects_noise_filter")
set(radar_crossing_objects_noise_filter_VERSION "0.1.0")
set(radar_crossing_objects_noise_filter_MAINTAINER "Sathshi Tanaka <satoshi.tanaka@tier4.jp>, Shunsuke Miura <shunsuke.miura@tier4.jp>, Yoshi Ri <yoshi.ri@tier4.jp>")
set(radar_crossing_objects_noise_filter_BUILD_DEPENDS "autoware_cmake" "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_crossing_objects_noise_filter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(radar_crossing_objects_noise_filter_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_crossing_objects_noise_filter_BUILDTOOL_EXPORT_DEPENDS )
set(radar_crossing_objects_noise_filter_EXEC_DEPENDS "autoware_auto_perception_msgs" "geometry_msgs" "rclcpp" "rclcpp_components" "tf2" "tf2_geometry_msgs" "tier4_autoware_utils")
set(radar_crossing_objects_noise_filter_TEST_DEPENDS "ament_lint_auto" "autoware_lint_common")
set(radar_crossing_objects_noise_filter_GROUP_DEPENDS )
set(radar_crossing_objects_noise_filter_MEMBER_OF_GROUPS )
set(radar_crossing_objects_noise_filter_DEPRECATED "")
set(radar_crossing_objects_noise_filter_EXPORT_TAGS)
list(APPEND radar_crossing_objects_noise_filter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
