set(_AMENT_PACKAGE_NAME "eagleye_gnss_converter")
set(eagleye_gnss_converter_VERSION "1.0.0")
set(eagleye_gnss_converter_MAINTAINER "OsamuSekino <osamu.sekino@tier4.jp>")
set(eagleye_gnss_converter_BUILD_DEPENDS "rclcpp" "sensor_msgs" "nmea_msgs" "ublox_msgs" "rtklib_msgs" "eagleye_coordinate" "eagleye_navigation" "tf2_ros" "tf2_geometry_msgs")
set(eagleye_gnss_converter_BUILDTOOL_DEPENDS "ament_cmake_auto")
set(eagleye_gnss_converter_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "nmea_msgs" "ublox_msgs" "rtklib_msgs" "eagleye_coordinate" "eagleye_navigation" "tf2_ros" "tf2_geometry_msgs")
set(eagleye_gnss_converter_BUILDTOOL_EXPORT_DEPENDS )
set(eagleye_gnss_converter_EXEC_DEPENDS "rclcpp" "sensor_msgs" "nmea_msgs" "ublox_msgs" "rtklib_msgs" "eagleye_coordinate" "eagleye_navigation" "tf2_ros" "tf2_geometry_msgs")
set(eagleye_gnss_converter_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(eagleye_gnss_converter_GROUP_DEPENDS )
set(eagleye_gnss_converter_MEMBER_OF_GROUPS )
set(eagleye_gnss_converter_DEPRECATED "")
set(eagleye_gnss_converter_EXPORT_TAGS)
list(APPEND eagleye_gnss_converter_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
