set(_AMENT_PACKAGE_NAME "lidar_apollo_instance_segmentation")
set(lidar_apollo_instance_segmentation_VERSION "0.1.0")
set(lidar_apollo_instance_segmentation_MAINTAINER "Yukihiro Saito <yukihiro.saito@tier4.jp>")
set(lidar_apollo_instance_segmentation_BUILD_DEPENDS "autoware_auto_perception_msgs" "cuda_utils" "libpcl-all-dev" "pcl_conversions" "rclcpp" "rclcpp_components" "tensorrt_common" "tf2_eigen" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_perception_msgs")
set(lidar_apollo_instance_segmentation_BUILDTOOL_DEPENDS "ament_cmake")
set(lidar_apollo_instance_segmentation_BUILD_EXPORT_DEPENDS "autoware_auto_perception_msgs" "cuda_utils" "libpcl-all-dev" "pcl_conversions" "rclcpp" "rclcpp_components" "tensorrt_common" "tf2_eigen" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_perception_msgs")
set(lidar_apollo_instance_segmentation_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_apollo_instance_segmentation_EXEC_DEPENDS "autoware_auto_perception_msgs" "cuda_utils" "libpcl-all-dev" "pcl_conversions" "rclcpp" "rclcpp_components" "tensorrt_common" "tf2_eigen" "tier4_autoware_utils" "tier4_debug_msgs" "tier4_perception_msgs")
set(lidar_apollo_instance_segmentation_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(lidar_apollo_instance_segmentation_GROUP_DEPENDS )
set(lidar_apollo_instance_segmentation_MEMBER_OF_GROUPS )
set(lidar_apollo_instance_segmentation_DEPRECATED "")
set(lidar_apollo_instance_segmentation_EXPORT_TAGS)
list(APPEND lidar_apollo_instance_segmentation_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
