// Generated by gencpp from file mcity_msg/OnePath.msg
// DO NOT EDIT!


#ifndef MCITY_MSG_MESSAGE_ONEPATH_H
#define MCITY_MSG_MESSAGE_ONEPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mcity_msg/Point.h>

namespace mcity_msg
{
template <class ContainerAllocator>
struct OnePath_
{
  typedef OnePath_<ContainerAllocator> Type;

  OnePath_()
    : data()  {
    }
  OnePath_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mcity_msg::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mcity_msg::Point_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mcity_msg::OnePath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcity_msg::OnePath_<ContainerAllocator> const> ConstPtr;

}; // struct OnePath_

typedef ::mcity_msg::OnePath_<std::allocator<void> > OnePath;

typedef boost::shared_ptr< ::mcity_msg::OnePath > OnePathPtr;
typedef boost::shared_ptr< ::mcity_msg::OnePath const> OnePathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcity_msg::OnePath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcity_msg::OnePath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcity_msg::OnePath_<ContainerAllocator1> & lhs, const ::mcity_msg::OnePath_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcity_msg::OnePath_<ContainerAllocator1> & lhs, const ::mcity_msg::OnePath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcity_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::OnePath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::OnePath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::OnePath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::OnePath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::OnePath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::OnePath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcity_msg::OnePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9c0ea2b2065370f4fa5c65f4cca313a";
  }

  static const char* value(const ::mcity_msg::OnePath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9c0ea2b2065370fULL;
  static const uint64_t static_value2 = 0x4fa5c65f4cca313aULL;
};

template<class ContainerAllocator>
struct DataType< ::mcity_msg::OnePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcity_msg/OnePath";
  }

  static const char* value(const ::mcity_msg::OnePath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcity_msg::OnePath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point[] data\n"
"================================================================================\n"
"MSG: mcity_msg/Point\n"
"float64 t\n"
"float64 x\n"
"float64 y\n"
"float64 v\n"
"float64 heading\n"
"float64 cr\n"
;
  }

  static const char* value(const ::mcity_msg::OnePath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcity_msg::OnePath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OnePath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcity_msg::OnePath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcity_msg::OnePath_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mcity_msg::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCITY_MSG_MESSAGE_ONEPATH_H
