// Generated by gencpp from file mcity_msg/PlanedPath.msg
// DO NOT EDIT!


#ifndef MCITY_MSG_MESSAGE_PLANEDPATH_H
#define MCITY_MSG_MESSAGE_PLANEDPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcity_msg
{
template <class ContainerAllocator>
struct PlanedPath_
{
  typedef PlanedPath_<ContainerAllocator> Type;

  PlanedPath_()
    : timestamp(0.0)
    , Estop(0)
    , Go(false)
    , Signal(0)
    , vd(0.0)
    , acc_d(0.0)
    , acc_dd(0.0)
    , slope(0.0)
    , vmax(0.0)
    , ey(0.0)
    , ephi(0.0)
    , len(0.0)
    , crVector()  {
    }
  PlanedPath_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , Estop(0)
    , Go(false)
    , Signal(0)
    , vd(0.0)
    , acc_d(0.0)
    , acc_dd(0.0)
    , slope(0.0)
    , vmax(0.0)
    , ey(0.0)
    , ephi(0.0)
    , len(0.0)
    , crVector(_alloc)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int16_t _Estop_type;
  _Estop_type Estop;

   typedef uint8_t _Go_type;
  _Go_type Go;

   typedef int16_t _Signal_type;
  _Signal_type Signal;

   typedef double _vd_type;
  _vd_type vd;

   typedef double _acc_d_type;
  _acc_d_type acc_d;

   typedef double _acc_dd_type;
  _acc_dd_type acc_dd;

   typedef double _slope_type;
  _slope_type slope;

   typedef double _vmax_type;
  _vmax_type vmax;

   typedef double _ey_type;
  _ey_type ey;

   typedef double _ephi_type;
  _ephi_type ephi;

   typedef double _len_type;
  _len_type len;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _crVector_type;
  _crVector_type crVector;





  typedef boost::shared_ptr< ::mcity_msg::PlanedPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcity_msg::PlanedPath_<ContainerAllocator> const> ConstPtr;

}; // struct PlanedPath_

typedef ::mcity_msg::PlanedPath_<std::allocator<void> > PlanedPath;

typedef boost::shared_ptr< ::mcity_msg::PlanedPath > PlanedPathPtr;
typedef boost::shared_ptr< ::mcity_msg::PlanedPath const> PlanedPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcity_msg::PlanedPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcity_msg::PlanedPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcity_msg::PlanedPath_<ContainerAllocator1> & lhs, const ::mcity_msg::PlanedPath_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.Estop == rhs.Estop &&
    lhs.Go == rhs.Go &&
    lhs.Signal == rhs.Signal &&
    lhs.vd == rhs.vd &&
    lhs.acc_d == rhs.acc_d &&
    lhs.acc_dd == rhs.acc_dd &&
    lhs.slope == rhs.slope &&
    lhs.vmax == rhs.vmax &&
    lhs.ey == rhs.ey &&
    lhs.ephi == rhs.ephi &&
    lhs.len == rhs.len &&
    lhs.crVector == rhs.crVector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcity_msg::PlanedPath_<ContainerAllocator1> & lhs, const ::mcity_msg::PlanedPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcity_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::PlanedPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::PlanedPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::PlanedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::PlanedPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::PlanedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::PlanedPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcity_msg::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49bda772fee12d71c5397d71f25fc583";
  }

  static const char* value(const ::mcity_msg::PlanedPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49bda772fee12d71ULL;
  static const uint64_t static_value2 = 0xc5397d71f25fc583ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcity_msg::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcity_msg/PlanedPath";
  }

  static const char* value(const ::mcity_msg::PlanedPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcity_msg::PlanedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 timestamp\n"
"int16 	Estop\n"
"bool 	Go\n"
"int16 	Signal\n"
"\n"
"float64 vd\n"
"float64 acc_d\n"
"float64 acc_dd\n"
"float64 slope\n"
"float64 vmax\n"
"float64 ey\n"
"float64 ephi\n"
"float64 len\n"
"float64[] crVector\n"
;
  }

  static const char* value(const ::mcity_msg::PlanedPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcity_msg::PlanedPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.Estop);
      stream.next(m.Go);
      stream.next(m.Signal);
      stream.next(m.vd);
      stream.next(m.acc_d);
      stream.next(m.acc_dd);
      stream.next(m.slope);
      stream.next(m.vmax);
      stream.next(m.ey);
      stream.next(m.ephi);
      stream.next(m.len);
      stream.next(m.crVector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanedPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcity_msg::PlanedPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcity_msg::PlanedPath_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "Estop: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Estop);
    s << indent << "Go: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Go);
    s << indent << "Signal: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Signal);
    s << indent << "vd: ";
    Printer<double>::stream(s, indent + "  ", v.vd);
    s << indent << "acc_d: ";
    Printer<double>::stream(s, indent + "  ", v.acc_d);
    s << indent << "acc_dd: ";
    Printer<double>::stream(s, indent + "  ", v.acc_dd);
    s << indent << "slope: ";
    Printer<double>::stream(s, indent + "  ", v.slope);
    s << indent << "vmax: ";
    Printer<double>::stream(s, indent + "  ", v.vmax);
    s << indent << "ey: ";
    Printer<double>::stream(s, indent + "  ", v.ey);
    s << indent << "ephi: ";
    Printer<double>::stream(s, indent + "  ", v.ephi);
    s << indent << "len: ";
    Printer<double>::stream(s, indent + "  ", v.len);
    s << indent << "crVector[]" << std::endl;
    for (size_t i = 0; i < v.crVector.size(); ++i)
    {
      s << indent << "  crVector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.crVector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCITY_MSG_MESSAGE_PLANEDPATH_H
