// Generated by gencpp from file mcity_msg/PointVec.msg
// DO NOT EDIT!


#ifndef MCITY_MSG_MESSAGE_POINTVEC_H
#define MCITY_MSG_MESSAGE_POINTVEC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mcity_msg/Point.h>

namespace mcity_msg
{
template <class ContainerAllocator>
struct PointVec_
{
  typedef PointVec_<ContainerAllocator> Type;

  PointVec_()
    : timestamp(0.0)
    , data()
    , ey(0.0)
    , ephi(0.0)  {
    }
  PointVec_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , data(_alloc)
    , ey(0.0)
    , ephi(0.0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::mcity_msg::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mcity_msg::Point_<ContainerAllocator> >::other >  _data_type;
  _data_type data;

   typedef double _ey_type;
  _ey_type ey;

   typedef double _ephi_type;
  _ephi_type ephi;





  typedef boost::shared_ptr< ::mcity_msg::PointVec_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcity_msg::PointVec_<ContainerAllocator> const> ConstPtr;

}; // struct PointVec_

typedef ::mcity_msg::PointVec_<std::allocator<void> > PointVec;

typedef boost::shared_ptr< ::mcity_msg::PointVec > PointVecPtr;
typedef boost::shared_ptr< ::mcity_msg::PointVec const> PointVecConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcity_msg::PointVec_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcity_msg::PointVec_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcity_msg::PointVec_<ContainerAllocator1> & lhs, const ::mcity_msg::PointVec_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.data == rhs.data &&
    lhs.ey == rhs.ey &&
    lhs.ephi == rhs.ephi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcity_msg::PointVec_<ContainerAllocator1> & lhs, const ::mcity_msg::PointVec_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcity_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::PointVec_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::PointVec_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::PointVec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::PointVec_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::PointVec_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::PointVec_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcity_msg::PointVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21741cd4518945400a6b176baa841311";
  }

  static const char* value(const ::mcity_msg::PointVec_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21741cd451894540ULL;
  static const uint64_t static_value2 = 0x0a6b176baa841311ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcity_msg::PointVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcity_msg/PointVec";
  }

  static const char* value(const ::mcity_msg::PointVec_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcity_msg::PointVec_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 timestamp\n"
"Point[] data\n"
"float64 ey\n"
"float64 ephi\n"
"================================================================================\n"
"MSG: mcity_msg/Point\n"
"float64 t\n"
"float64 x\n"
"float64 y\n"
"float64 v\n"
"float64 heading\n"
"float64 cr\n"
;
  }

  static const char* value(const ::mcity_msg::PointVec_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcity_msg::PointVec_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.data);
      stream.next(m.ey);
      stream.next(m.ephi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointVec_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcity_msg::PointVec_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcity_msg::PointVec_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mcity_msg::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
    s << indent << "ey: ";
    Printer<double>::stream(s, indent + "  ", v.ey);
    s << indent << "ephi: ";
    Printer<double>::stream(s, indent + "  ", v.ephi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCITY_MSG_MESSAGE_POINTVEC_H
