// Generated by gencpp from file mcity_msg/SPaT.msg
// DO NOT EDIT!


#ifndef MCITY_MSG_MESSAGE_SPAT_H
#define MCITY_MSG_MESSAGE_SPAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcity_msg
{
template <class ContainerAllocator>
struct SPaT_
{
  typedef SPaT_<ContainerAllocator> Type;

  SPaT_()
    : timestamp(0.0)
    , id(0)
    , state()
    , remain_time()  {
      state.assign(0);

      remain_time.assign(0.0);
  }
  SPaT_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , id(0)
    , state()
    , remain_time()  {
  (void)_alloc;
      state.assign(0);

      remain_time.assign(0.0);
  }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _id_type;
  _id_type id;

   typedef boost::array<int16_t, 8>  _state_type;
  _state_type state;

   typedef boost::array<float, 8>  _remain_time_type;
  _remain_time_type remain_time;





  typedef boost::shared_ptr< ::mcity_msg::SPaT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcity_msg::SPaT_<ContainerAllocator> const> ConstPtr;

}; // struct SPaT_

typedef ::mcity_msg::SPaT_<std::allocator<void> > SPaT;

typedef boost::shared_ptr< ::mcity_msg::SPaT > SPaTPtr;
typedef boost::shared_ptr< ::mcity_msg::SPaT const> SPaTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcity_msg::SPaT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcity_msg::SPaT_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mcity_msg::SPaT_<ContainerAllocator1> & lhs, const ::mcity_msg::SPaT_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.id == rhs.id &&
    lhs.state == rhs.state &&
    lhs.remain_time == rhs.remain_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mcity_msg::SPaT_<ContainerAllocator1> & lhs, const ::mcity_msg::SPaT_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mcity_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::SPaT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcity_msg::SPaT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::SPaT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcity_msg::SPaT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::SPaT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcity_msg::SPaT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcity_msg::SPaT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eb424f842fa66753b100ed886f5a19c";
  }

  static const char* value(const ::mcity_msg::SPaT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eb424f842fa6675ULL;
  static const uint64_t static_value2 = 0x3b100ed886f5a19cULL;
};

template<class ContainerAllocator>
struct DataType< ::mcity_msg::SPaT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcity_msg/SPaT";
  }

  static const char* value(const ::mcity_msg::SPaT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcity_msg::SPaT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 	timestamp\n"
"int32 		id \n"
"int16[8] 	state\n"
"float32[8] 	remain_time\n"
"\n"
"#define state\n"
"#RED 		1\n"
"#GREEN		3\n"
"#YELLOW  	4\n"
;
  }

  static const char* value(const ::mcity_msg::SPaT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcity_msg::SPaT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.id);
      stream.next(m.state);
      stream.next(m.remain_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPaT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcity_msg::SPaT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcity_msg::SPaT_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.state[i]);
    }
    s << indent << "remain_time[]" << std::endl;
    for (size_t i = 0; i < v.remain_time.size(); ++i)
    {
      s << indent << "  remain_time[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.remain_time[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCITY_MSG_MESSAGE_SPAT_H
