set(_AMENT_PACKAGE_NAME "landmark_tf_caster")
set(landmark_tf_caster_VERSION "0.0.0")
set(landmark_tf_caster_MAINTAINER "Shintaro Sakoda <shintaro.sakoda@tier4.jp>, Masahiro Sakamoto <masahiro.sakamoto@tier4.jp>")
set(landmark_tf_caster_BUILD_DEPENDS "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "libopencv-dev" "rclcpp" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros")
set(landmark_tf_caster_BUILDTOOL_DEPENDS "ament_cmake" "autoware_cmake")
set(landmark_tf_caster_BUILD_EXPORT_DEPENDS "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "libopencv-dev" "rclcpp" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros")
set(landmark_tf_caster_BUILDTOOL_EXPORT_DEPENDS )
set(landmark_tf_caster_EXEC_DEPENDS "autoware_auto_mapping_msgs" "geometry_msgs" "lanelet2_extension" "libopencv-dev" "rclcpp" "tf2_eigen" "tf2_geometry_msgs" "tf2_ros")
set(landmark_tf_caster_TEST_DEPENDS )
set(landmark_tf_caster_GROUP_DEPENDS )
set(landmark_tf_caster_MEMBER_OF_GROUPS )
set(landmark_tf_caster_DEPRECATED "")
set(landmark_tf_caster_EXPORT_TAGS)
list(APPEND landmark_tf_caster_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
