set(_AMENT_PACKAGE_NAME "mcity_localization")
set(mcity_localization_VERSION "1.0.0")
set(mcity_localization_MAINTAINER "Zhijie Qiao <zhijieq@umich.edu>")
set(mcity_localization_BUILD_DEPENDS "rclpy" "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "geometry_msgs")
set(mcity_localization_BUILDTOOL_DEPENDS "ament_cmake_auto" "autoware_cmake")
set(mcity_localization_BUILD_EXPORT_DEPENDS "rclpy" "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "geometry_msgs")
set(mcity_localization_BUILDTOOL_EXPORT_DEPENDS )
set(mcity_localization_EXEC_DEPENDS "ros2launch" "rclpy" "rclcpp" "rclcpp_components" "std_msgs" "nav_msgs" "sensor_msgs" "geometry_msgs")
set(mcity_localization_TEST_DEPENDS "ament_lint_auto")
set(mcity_localization_GROUP_DEPENDS )
set(mcity_localization_MEMBER_OF_GROUPS )
set(mcity_localization_DEPRECATED "")
set(mcity_localization_EXPORT_TAGS)
list(APPEND mcity_localization_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
